const assert = require('node:assert/strict');
const fs = require('node:fs');
const { chromium } = require('playwright');
(async () => {
    const info = JSON.parse(await new Promise(resolve => { let s = ''; process.stdin.on('data', x => s += x); process.stdin.on('end', () => resolve(s)); }));
    const browser = await chromium.launch({ channel: 'chrome', headless: true });
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    const page = await context.newPage();
    const errors = []; page.on('pageerror', e => errors.push(e.message)); page.setDefaultTimeout(25000);
    fs.mkdirSync('TestResults/customer-deposit', { recursive: true });
    try {
        await page.goto(info.baseUrl + '/admin/account/login');
        await page.locator('[name=UserName]').fill(info.user);
        await page.locator('[name=Password]').fill(info.password);
        await page.locator('select[name=SelectedTerminalId]').selectOption(String(info.terminalId));
        await Promise.all([page.waitForURL(u => !u.pathname.endsWith('/login')), page.locator('#loginForm button[type=submit]').click()]);
        const customerDisplay = await context.newPage();
        await customerDisplay.goto(info.baseUrl + '/admin/pos/customer-display');
        await customerDisplay.locator('#customerDisplayApp').waitFor();
        await page.goto(info.baseUrl + '/admin/customer-deposit');
        let customerSearchRequests = 0;
        page.on('request', request => { if (request.url().includes('/customer-deposit/customers/search')) customerSearchRequests++; });
        const customerSearchInput = page.locator('#depositCustomerSearch');
        await customerSearchInput.fill('K');
        await page.waitForTimeout(350);
        assert.equal(customerSearchRequests, 0, 'One character must not query the customer search endpoint.');
        const customerSearchResponse = page.waitForResponse(r => r.url().includes('/customer-deposit/customers/search'));
        await customerSearchInput.fill('Khách công nợ');
        assert.equal((await customerSearchResponse).status(), 200);
        await page.locator('[data-customer-result]').first().waitFor();
        await page.screenshot({ path: 'TestResults/customer-deposit/autocomplete.png', fullPage: true });
        await customerSearchInput.press('ArrowDown');
        await Promise.all([
            page.waitForURL(url => url.searchParams.get('customerId') === String(info.customerId)),
            customerSearchInput.press('Enter')
        ]);
        await page.locator('#depositReceive [name=purpose]').fill('Đặt hàng giao khi có hàng');
        let qrRequestCount = 0;
        page.on('request', request => { if (request.url().endsWith('/customer-deposit/receive-qr')) qrRequestCount++; });
        await page.locator('#depositReceive [name=method][value="1"]').check({ force: true });
        await page.locator('#depositReceive [name=amount]').fill('4');
        await page.locator('#depositReceive [name=amount]').fill('40');
        await page.waitForTimeout(500);
        assert.equal(qrRequestCount, 0, 'Entering the amount must not create QR automatically.');
        const qrPreview = page.waitForResponse(r => r.url().endsWith('/customer-deposit/receive-qr'));
        await page.locator('#depositCreateQr').click();
        const qrResponse = await qrPreview; assert.equal(qrResponse.status(), 200, await qrResponse.text());
        assert.equal(qrRequestCount, 1);
        await page.locator('#depositQrPreview .deposit-qr-preview__content').waitFor();
        assert.match(await page.locator('#depositQrImage').getAttribute('src'), /^data:image\/png;base64,/);
        await customerDisplay.getByText('Quét mã để đặt cọc', { exact: true }).waitFor();
        assert.match(await customerDisplay.locator('#cdQrImage').getAttribute('src'), /^data:image\/png;base64,/);
        await page.screenshot({ path: 'TestResults/customer-deposit/receive-qr.png', fullPage: true });
        await customerDisplay.screenshot({ path: 'TestResults/customer-deposit/customer-display-qr.png', fullPage: true });
        await page.locator('#depositReceive input[type=checkbox]').check();
        const receipt = page.waitForResponse(r => r.url().endsWith('/customer-deposit/receive'));
        await page.locator('#depositReceive button[type="submit"]').click();
        const response = await receipt; assert.equal(response.status(), 200);
        await page.waitForLoadState('networkidle');
        await page.locator('[data-deposit-tab="journal"]').click();
        await page.getByText('PCOC-1', { exact: false }).waitFor();
        await page.waitForTimeout(300);
        const depositId = Number(await page.locator('#depositRefund [name=depositId]').inputValue());
        await page.screenshot({ path: 'TestResults/customer-deposit/ledger.png', fullPage: true });
        await page.setViewportSize({ width: 390, height: 844 });
        await page.screenshot({ path: 'TestResults/customer-deposit/mobile.png', fullPage: true });
        await page.setViewportSize({ width: 1440, height: 1000 });
        await page.goto(info.baseUrl + '/admin/pos');
        await page.waitForFunction(() => window.posApp?.state.business.currentDraft?.lines?.length && window.PosOffline?.status().ready);
        await page.locator('#btnOpenPayment').click();
        assert.equal(await page.locator('#posDepositPanel').isVisible(), false);
        assert.equal(await page.evaluate(async id => {
            const r = await fetch('/admin/pos/cart/current/customer/' + id, { method: 'POST', headers: { 'Content-Type': 'application/json', RequestVerificationToken: document.querySelector('[name=__RequestVerificationToken]').value }, body: JSON.stringify({ repriceExistingLines: false }) }); return r.ok;
        }, info.customerId), true);
        await page.reload();
        await page.waitForFunction(() => window.posApp?.state.business.currentDraft?.customerId && window.PosOffline?.status().ready);
        const apply = page.waitForResponse(r => r.url().endsWith('/select') && r.request().method() === 'POST');
        await page.locator('#btnOpenPayment').click();
        await page.locator('#posDepositPanel').waitFor();
        const applied = await apply; assert.equal(applied.status(), 200, await applied.text());
        await page.waitForFunction(() => window.posApp.state.business.currentDraft.depositAmount === 40);
        assert.equal(await page.locator('#posDepositChoice').inputValue(), String(depositId));
        assert.equal(await page.evaluate(() => window.posApp.state.business.currentDraft.balanceDue), 20);
        assert.equal(await page.locator('#payAmount').inputValue(), '20');
        await page.screenshot({ path: 'TestResults/customer-deposit/payment.png', fullPage: true });
        await page.keyboard.press('Alt+4');
        await page.locator('#btnCreditPayment.is-active').waitFor();
        assert.equal(await page.locator('#btnFinalizeFromPaymentModal').textContent(), 'Chốt đơn và ghi công nợ');
        await page.screenshot({ path: 'TestResults/customer-deposit/credit.png', fullPage: true });
        assert.equal(await page.locator('#creditDueDate').count(), 0);
        const finalized = page.waitForResponse(r => r.url().includes('/finalize-credit'));
        await page.locator('#btnFinalizeFromPaymentModal').click();
        const final = await finalized; assert.equal(final.status(), 200, await final.text());
        await page.goto(info.baseUrl + '/admin/customer-deposit?customerId=' + info.customerId);
        await page.locator('[data-deposit-tab="journal"]').click();
        await page.getByText('Dùng cọc', { exact: true }).waitFor();
        await page.goto(info.baseUrl + '/admin/pos/order-detail/' + info.orderId);
        await page.locator('[onclick*="openReturnRefundModal"]').click();
        await page.locator('#refundMethod option[value="100"]').waitFor({ state: 'attached' });
        await page.locator('.js-return-qty').first().fill('3');
        await page.locator('.js-return-qty').first().dispatchEvent('input');
        await page.locator('#refundMethod').selectOption('100');
        await page.locator('#returnReason').fill('Hoàn cọc trên giao diện');
        const returned = page.waitForResponse(r => r.url().endsWith('/admin/pos/returns') && r.request().method() === 'POST');
        await page.locator('#btnSubmitReturnRefund').click();
        const returnResponse = await returned; assert.equal(returnResponse.status(), 200, await returnResponse.text());
        await page.goto(info.baseUrl + '/admin/customer-deposit?customerId=' + info.customerId);
        await page.locator('[data-deposit-tab="journal"]').click();
        await page.getByText('Trả hàng hoàn vào cọc', { exact: true }).waitFor();
        assert.deepEqual(errors, []);
        console.log('PASS: receive deposit by QR, redesigned desktop/mobile, automatic deposit use, Alt+4 credit finalization and journal.');
    } catch (error) { console.error('PAGE_ERRORS', errors); await page.screenshot({ path: 'TestResults/customer-deposit/failure.png', fullPage: true }); throw error; }
    finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
