const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
(async()=>{const info=JSON.parse(await new Promise(r=>{let s='';process.stdin.on('data',x=>s+=x);process.stdin.on('end',()=>r(s));}));
const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:1480,height:1080}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const output=path.resolve('TestResults/customer-profile');fs.mkdirSync(output,{recursive:true});
const loaded=async()=>{await page.waitForFunction(()=>document.getElementById('cpResults')?.getAttribute('aria-busy')==='false');assert.equal(await page.locator('[data-retry]').count(),0,await page.locator('#cpResults').innerText());};
try{await page.goto(info.baseUrl+'/admin/account/login');await page.locator('[name=UserName]').fill(info.user);await page.locator('[name=Password]').fill(info.password);if(await page.locator('[name=SelectedTerminalId]').count())await page.locator('[name=SelectedTerminalId]').selectOption(String(info.terminalId));await Promise.all([page.waitForURL(u=>!u.pathname.endsWith('/login')),page.locator('button[type=submit]').click()]);
await page.goto(info.baseUrl+'/Admin/Customer?searchString=KH-PROFILE');await page.locator(`a.customer-name[href="/admin/customers/${info.customerId}/profile"]`).click();await loaded();assert.equal((await page.locator('#cpPoints').innerText()).trim(),'11');assert.equal(await page.locator('.cp-activity').count(),20);await page.screenshot({path:path.join(output,'overview.png'),fullPage:true});
await page.locator('[data-tab=points]').click();await loaded();assert.equal(await page.locator('.cp-table tbody tr').count(),20);await page.locator('#cpNext').click();await loaded();assert.equal(await page.locator('.cp-table tbody tr').count(),3);
await page.locator('#cpStatus').selectOption('4');await page.locator('#cpFrom').fill('2026-09-03');await page.locator('#cpTo').fill('2026-09-03');await page.locator('#cpFilters button[type=submit]').click();await loaded();assert.equal(await page.locator('.cp-table tbody tr').count(),1);assert.match(await page.locator('.cp-table tbody').innerText(),/9 điểm/);assert.equal((await page.locator('#cpPoints').innerText()).trim(),'11');await page.screenshot({path:path.join(output,'points.png'),fullPage:true});
await page.locator('[data-tab=vouchers]').click();await loaded();await page.locator(`[data-voucher="${info.voucherId}"]`).first().click();await page.waitForFunction(()=>document.getElementById('cpDetailTitle').textContent==='VC-PROFILE-USED');assert.match(await page.locator('#cpDetailBody').innerText(),/Đã dùng/);await page.locator('#cpCloseDetail').click();
await page.locator('[data-tab=orders]').click();await loaded();await page.locator(`[data-order="${info.orderId}"]`).first().click();await page.waitForFunction(()=>document.getElementById('cpDetailTitle').textContent==='PROFILE-SALE');assert.match(await page.locator('#cpDetailBody').innerText(),/100.000/);await page.locator('#cpCloseDetail').click();
await page.locator('#cpSearch').fill('NO-MATCH');await page.locator('#cpFilters button[type=submit]').click();await loaded();assert.match(await page.locator('#cpResults').innerText(),/Chưa có giao dịch/);await page.locator('#cpClear').click();await loaded();
await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
await page.setViewportSize({width:1480,height:1080});await page.goto(info.baseUrl+'/admin/pos');await page.waitForFunction(()=>window.PosRender?.renderCustomerInfo);await page.evaluate(id=>window.PosRender.renderCustomerInfo({customerId:id,customerName:'Nguyễn Minh An'}),info.customerId);const profileLink=page.locator('#customerInfoBox .pos-customer-profile-link');
assert.equal(await profileLink.getAttribute('target'),'_blank');
assert.ok(await profileLink.isVisible(),'POS history action must be visible, not inside a hidden hint');
await page.setViewportSize({width:1280,height:800});
await page.screenshot({path:path.join(output,'pos-history.png'),fullPage:true});
const [profileTab]=await Promise.all([context.waitForEvent('page'),profileLink.click()]);
await profileTab.waitForLoadState('domcontentloaded');
assert.ok(profileTab.url().endsWith(`/admin/customers/${info.customerId}/profile`));
assert.ok(await profileTab.locator('#customerProfile').isVisible());
await profileTab.close();
await page.goto(info.baseUrl+'/admin/pos/legacy');
await page.waitForFunction(()=>window.PosRender?.renderCustomerInfo);
await page.evaluate(id=>window.PosRender.renderCustomerInfo({customerId:id,customerName:'Nguyễn Minh An'}),info.customerId);
assert.ok(await profileLink.isVisible(),'Legacy POS history action must be visible');
await page.evaluate(()=>{document.getElementById('posCustomerProfileAccess').dataset.allowed='false';window.PosRender.renderCustomerInfo({customerId:1,customerName:'Khách thử'});});
assert.equal(await profileLink.count(),0,'Do not expose action without Customer.View');
assert.deepEqual(errors,[]);
console.log('PASS: customer link, overview, points balance, filtered running totals, pagination, voucher/order previews, empty state, mobile layout and POS link.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
