'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
(async () => {
    const info = JSON.parse(await new Promise(resolve => { let text = ''; process.stdin.on('data', value => text += value); process.stdin.on('end', () => resolve(text)); }));
    const output = path.resolve('TestResults/product-labels/browser'); fs.mkdirSync(output, { recursive: true });
    const browser = await chromium.launch({ channel: 'chrome', headless: true });
    const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
    let page = await context.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message));
    // Mock only installed printer discovery. All template/receipt/job APIs and SQL are real.
    await page.route('**/admin/label-printing/installed-printers', route => route.fulfill({ json: ['Xprinter 420B TEST USB'] }));
    const request = (url, method = 'GET', body) => page.evaluate(async ({ url, method, body }) => {
        const response = await fetch(url, { method, headers: { 'Content-Type': 'application/json', RequestVerificationToken: document.querySelector('[name="__RequestVerificationToken"]').value }, body: body === undefined ? undefined : JSON.stringify(body) });
        const text = await response.text(); if (!response.ok) throw new Error(response.status + ': ' + text); return text ? JSON.parse(text) : null;
    }, { url, method, body });
    async function login(target, credentials) {
        await target.goto(info.baseUrl + '/admin/account/login');
        await target.locator('[name=UserName]').fill(credentials.user); await target.locator('[name=Password]').fill(credentials.password);
        if (await target.locator('select[name=SelectedTerminalId]').count()) await target.locator('select[name=SelectedTerminalId]').selectOption(String(info.terminalId));
        await Promise.all([target.waitForURL(url => !url.pathname.endsWith('/login')), target.locator('#loginForm button[type=submit]').click()]);
    }
    try {
        await login(page, info);
        await page.goto(info.baseUrl + '/admin/label-printing');
        assert.equal(await page.locator('#layout-menu a[href="/admin/label-printing"]').count(), 1);
        assert.equal(await page.locator('#layout-menu a[href="/admin/label-printing-settings"]').count(), 1);
        assert.equal(await page.locator('#templateFields, #printerForm').count(), 0);
        assert.deepEqual(await page.locator('.label-tabs [data-tab]').evaluateAll(xs => xs.map(x => x.dataset.tab)), ['tasks', 'history']);
        await page.locator('#labelPrinting a[href="/admin/label-printing-settings"]').click();
        await page.waitForURL('**/admin/label-printing-settings');
        assert.equal(await page.locator('#labelPrinting').getAttribute('data-page'), 'settings');
        assert.equal(await page.locator('#taskLines, #allHistory').count(), 0);
        assert.deepEqual(await page.locator('.label-tabs [data-tab]').evaluateAll(xs => xs.map(x => x.dataset.tab)), ['templates', 'printers']);
        await page.waitForFunction(() => [...document.querySelectorAll('#layoutGallery img')].length === 4 && [...document.querySelectorAll('#layoutGallery img')].every(x => x.complete && x.naturalWidth > 0));
        assert.equal(await page.locator('#templateFields select[name=barcodeFormat]').count(), 0);
        assert.equal(await page.locator('#templateFields [name=barcodeFormat]').inputValue(), 'AUTO');
        const layouts = ['standard', 'price-first', 'price-tag', 'framed'];
        for (const layout of layouts) {
            const old = await page.locator('#labelPreview').getAttribute('src');
            await page.locator(`[data-layout="${layout}"]`).click();
            await page.waitForFunction(old => { const x = document.querySelector('#labelPreview'); return x.src !== old && !x.hidden && x.complete && x.naturalWidth > 0; }, old);
            assert.equal(await page.locator(`[data-layout="${layout}"]`).getAttribute('aria-pressed'), 'true');
            assert.equal(await page.locator('#templateFields [name=widthMm]').inputValue(), '35');
            assert.equal(await page.locator('#templateFields [name=columns]').inputValue(), '2');
            await page.locator('#labelPreview').screenshot({ path: path.join(output, `layout-${layout}-35.png`) });
        }
        await page.locator('#templateFields [name=name]').fill('Tem tiệm · 50 × 30 / hai cột');
        await page.locator('#templateFields [name=widthMm]').fill('50'); await page.locator('#templateFields [name=heightMm]').fill('30');
        assert.equal(await page.locator('#templateFields [name=columns]').inputValue(), '2');
        await page.locator('#templateFields [name=quantityMode]').selectOption('received');
        await page.locator('[data-layout="price-tag"]').click();
        assert.equal(await page.locator('#templateFields [name=widthMm]').inputValue(), '50');
        assert.equal(await page.locator('#templateFields [name=heightMm]').inputValue(), '30');
        assert.equal(await page.locator('#templateFields [name=quantityMode]').inputValue(), 'received');
        await Promise.all([page.waitForResponse(r => r.url().endsWith('/templates') && r.request().method() === 'POST' && r.ok()), page.locator('#saveTemplate').click()]);
        await page.waitForFunction(() => document.querySelector('#templateSaveState').textContent === 'Đã lưu');
        await page.locator('#previewTemplate').click(); await page.waitForFunction(() => !document.querySelector('#labelPreview').hidden && document.querySelector('#labelPreview').naturalWidth > 0);
        await page.screenshot({ path: path.join(output, 'template-50x30-two-columns.png'), fullPage: true });
        const saved = (await request('/admin/label-printing/templates'))[0];
        assert.equal(saved.design.columns, 2); assert.equal(saved.design.widthMm, 50); assert.equal(saved.design.quantityMode, 'received');
        assert.equal(saved.design.layout, 'price-tag'); assert.equal(saved.design.barcodeFormat, 'AUTO');
        await page.locator('#templateFields [name=columns]').fill('3'); await page.locator('#previewTemplate').click();
        await page.waitForFunction(() => document.querySelector('#previewError').textContent.includes('vượt vùng in'));
        await page.locator('#templateFields [name=columns]').fill('2'); await page.locator('#saveTemplate').click();
        await page.waitForFunction(() => document.querySelector('#templateSaveState').textContent === 'Đã lưu');
        await page.locator('[data-tab="printers"]').click();
        await page.locator('#printerForm [name=name]').fill('Xprinter kho hàng'); await page.locator('#printerForm [name=windowsPrinterName]').selectOption('Xprinter 420B TEST USB');
        await Promise.all([page.waitForResponse(r => r.url().endsWith('/printers') && r.request().method() === 'POST' && r.ok()), page.locator('#printerForm button[type=submit]').click()]);
        await page.goto(info.baseUrl + '/admin/stock-documents/' + info.receiptId);
        assert.equal(await page.locator('[data-label-add]').count(), 1);
        await Promise.all([page.waitForURL('**/admin/label-printing?task=*'), page.locator('[data-label-add]').click()]);
        const adminPage = page;
        const employeeContext = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
        page = await employeeContext.newPage(); page.on('pageerror', e => errors.push(e.message));
        const settingsRequests = [];
        page.on('request', r => { if (/\/installed-printers|\/layouts\//.test(r.url())) settingsRequests.push(r.url()); });
        await login(page, info.employee);
        await page.goto(info.baseUrl + '/admin/label-printing');
        assert.equal(await page.locator('#layout-menu a[href="/admin/label-printing"]').count(), 1);
        assert.equal(await page.locator('a[href="/admin/label-printing-settings"]').count(), 0);
        assert.equal(await page.locator('#templateFields, #printerForm, #printTest').count(), 0);
        assert.deepEqual(await page.locator('.label-tabs [data-tab]').evaluateAll(xs => xs.map(x => x.dataset.tab)), ['tasks', 'history']);
        const forbidden = await page.request.get(info.baseUrl + '/admin/label-printing-settings', { headers: { Accept: 'application/json' }, maxRedirects: 0 });
        assert.equal(forbidden.status(), 403);
        await page.locator('[data-task]').first().click();
        await page.waitForSelector('#taskLines tr');
        await page.locator('#taskTemplate').selectOption(String(saved.id));
        assert.equal(await page.locator('.required-qty').inputValue(), '48');
        await Promise.all([page.waitForResponse(r => r.url().endsWith('/plan') && r.ok()), page.locator('#savePlan').click()]);
        await page.waitForFunction(() => document.querySelector('#taskTotals').textContent.includes('/ 48'));
        const printers = await request('/admin/label-printing/printers'); await page.locator('#taskPrinter').selectOption(String(printers[0].id));
        await page.locator('.print-qty').fill('3'); await page.locator('#previewTask').click();
        await page.waitForSelector('#labelDialog[open] img'); await page.locator('#dialogClose').click();
        await page.locator('#printTask').click(); await page.locator('#dialogAccept').click();
        await page.waitForFunction(() => document.querySelector('#taskHistory').textContent.includes('Chờ server in'));
        const jobs = await request('/admin/label-printing/jobs'); assert.equal(jobs.length, 1); assert.equal(jobs[0].quantity, 3);
        assert.equal(jobs[0].payload.items[0].product.price, 12345); assert.equal(jobs[0].payload.items[0].product.unit, 'Chai');
        assert.equal(jobs[0].payload.design.layout, 'price-tag'); assert.equal(jobs[0].payload.design.barcodeFormat, 'AUTO');
        await page.screenshot({ path: path.join(output, 'receipt-queued.png'), fullPage: true });
        await page.locator('[data-cancel-job]').first().click(); await page.locator('#dialogAccept').click();
        await page.waitForFunction(() => document.querySelector('#taskHistory').textContent.includes('Đã hủy'));
        await page.reload(); await page.waitForSelector('#taskLines tr');
        assert.equal(await page.locator('.required-qty').inputValue(), '48');
        await page.screenshot({ path: path.join(output, 'staff-print-workspace.png'), fullPage: true });
        await page.setViewportSize({ width: 390, height: 844 });
        await page.screenshot({ path: path.join(output, 'staff-print-mobile.png'), fullPage: true });
        assert.equal(await page.locator('#labelPrinting').evaluate(x => x.scrollWidth > x.clientWidth + 2), false);
        assert.deepEqual(settingsRequests, []);
        page = adminPage;
        await page.goto(info.baseUrl + '/admin/label-printing-settings');
        await page.waitForFunction(() => document.querySelector('[data-layout="price-tag"]').getAttribute('aria-pressed') === 'true');
        assert.equal(await page.locator('[data-layout="price-tag"]').getAttribute('aria-pressed'), 'true');
        await page.locator('[data-layout="framed"]').click();
        await page.locator('#templateFields [name=name]').fill('Khung tiệm · 50 × 30');
        await page.locator('#copyTemplate').click();
        await page.waitForFunction(() => document.querySelector('#templateSaveState').textContent === 'Đã lưu');
        const copies = await request('/admin/label-printing/templates'); assert.equal(copies.length, 2);
        assert.equal(copies.find(x => x.id === saved.id).design.layout, 'price-tag');
        assert.equal(copies.find(x => x.id !== saved.id).design.layout, 'framed');
        await page.setViewportSize({ width: 390, height: 844 });
        await page.locator('#layoutGallery').scrollIntoViewIfNeeded();
        await page.waitForFunction(() => [...document.querySelectorAll('#layoutGallery img')].every(x => x.complete && x.naturalWidth > 0));
        await page.screenshot({ path: path.join(output, 'templates-mobile.png'), fullPage: true });
        const overflow = await page.locator('#labelPrinting').evaluate(x => x.scrollWidth > x.clientWidth + 2); assert.equal(overflow, false);
        assert.deepEqual(errors, []);
        console.log('PASS: separate admin settings and staff print pages/menus, staff forbidden from configuration, staff receipt queue/cancel/defaults, four layouts, AUTO, copy/persistence and responsive UI.');
    } catch (error) { await page.screenshot({ path: path.join(output, 'failure.png'), fullPage: true }); throw error; }
    finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
