'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
(async () => {
    const info = JSON.parse(await new Promise(resolve => { let text = ''; process.stdin.on('data', value => text += value); process.stdin.on('end', () => resolve(text)); }));
    const output = path.resolve('TestResults/product-labels/browser'); fs.mkdirSync(output, { recursive: true });
    const browser = await chromium.launch({ channel: 'chrome', headless: true });
    const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
    let page = await context.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message));
    // Mock only installed printer discovery. All template/receipt/job APIs and SQL are real.
    await page.route('**/admin/label-printing/installed-printers', route => route.fulfill({ json: ['Xprinter 420B TEST USB'] }));
    const request = (url, method = 'GET', body) => page.evaluate(async ({ url, method, body }) => {
        const response = await fetch(url, { method, headers: { 'Content-Type': 'application/json', RequestVerificationToken: document.querySelector('[name="__RequestVerificationToken"]').value }, body: body === undefined ? undefined : JSON.stringify(body) });
        const text = await response.text(); if (!response.ok) throw new Error(response.status + ': ' + text); return text ? JSON.parse(text) : null;
    }, { url, method, body });
    async function login(target, credentials) {
        await target.goto(info.baseUrl + '/admin/account/login');
        await target.locator('[name=UserName]').fill(credentials.user); await target.locator('[name=Password]').fill(credentials.password);
        if (await target.locator('select[name=SelectedTerminalId]').count()) await target.locator('select[name=SelectedTerminalId]').selectOption(String(info.terminalId));
        await Promise.all([target.waitForURL(url => !url.pathname.endsWith('/login')), target.locator('#loginForm button[type=submit]').click()]);
    }
    try {
        await login(page, info);
        await page.goto(info.baseUrl + '/admin/label-printing');
        assert.equal(await page.locator('#layout-menu a[href="/admin/label-printing"]').count(), 1);
        assert.equal(await page.locator('#layout-menu a[href="/admin/label-printing-settings"]').count(), 1);
        assert.equal(await page.locator('#templateFields, #printerForm').count(), 0);
        assert.deepEqual(await page.locator('.label-tabs [data-tab]').evaluateAll(xs => xs.map(x => x.dataset.tab)), ['quick', 'tasks', 'history']);
        await page.locator('#labelPrinting a[href="/admin/label-printing-settings"]').click();
        await page.waitForURL('**/admin/label-printing-settings');
        assert.equal(await page.locator('#labelPrinting').getAttribute('data-page'), 'settings');
        assert.equal(await page.locator('#taskLines, #allHistory').count(), 0);
        assert.deepEqual(await page.locator('.label-tabs [data-tab]').evaluateAll(xs => xs.map(x => x.dataset.tab)), ['templates', 'printers']);
        await page.waitForFunction(() => [...document.querySelectorAll('#layoutGallery img')].length === 5 && [...document.querySelectorAll('#layoutGallery img')].every(x => x.complete && x.naturalWidth > 0));
        assert.equal(await page.locator('#templateFields select[name=barcodeFormat]').count(), 0);
        assert.equal(await page.locator('#templateFields [name=barcodeFormat]').inputValue(), 'AUTO');
        await page.locator('[data-tab="printers"]').click();
        await page.locator('#printerForm [name=name]').fill('Xprinter kho hàng'); await page.locator('#printerForm [name=windowsPrinterName]').selectOption('Xprinter 420B TEST USB');
        await Promise.all([page.waitForResponse(r => r.url().endsWith('/printers') && r.request().method() === 'POST' && r.ok()), page.locator('#printerForm button[type=submit]').click()]);
        await page.locator('[data-tab=templates]').click();
        const printers = await request('/admin/label-printing/printers');
        await page.locator('#templatePrinter').selectOption(String(printers[0].id));
        const layouts = ['standard', 'price-first', 'price-tag', 'framed', 'retail-large'];
        for (const layout of layouts) {
            const old = await page.locator('#labelPreview').getAttribute('src');
            await page.locator(`[data-layout="${layout}"]`).click();
            await page.waitForFunction(old => { const x = document.querySelector('#labelPreview'); return x.src !== old && !x.hidden && x.complete && x.naturalWidth > 0; }, old);
            assert.equal(await page.locator(`[data-layout="${layout}"]`).getAttribute('aria-pressed'), 'true');
            assert.equal(await page.locator('#templateFields [name=widthMm]').inputValue(), layout === 'retail-large' ? '50' : '35');
            assert.equal(await page.locator('#templateFields [name=columns]').inputValue(), '2');
            await page.locator('#labelPreview').screenshot({ path: path.join(output, `layout-${layout}.png`) });
        }
        await page.locator('#templateFields [name=name]').fill('Tem tiệm · 50 × 30 / hai cột');
        await page.locator('#templateFields [name=widthMm]').fill('50'); await page.locator('#templateFields [name=heightMm]').fill('30');
        assert.equal(await page.locator('#templateFields [name=columns]').inputValue(), '2');
        await page.locator('#templateFields [name=quantityMode]').selectOption('received');
        await page.locator('[data-layout="price-tag"]').click();
        assert.equal(await page.locator('#templateFields [name=widthMm]').inputValue(), '50');
        assert.equal(await page.locator('#templateFields [name=heightMm]').inputValue(), '30');
        assert.equal(await page.locator('#templateFields [name=quantityMode]').inputValue(), 'received');
        await page.locator('#templatePrinter').selectOption(String(printers[0].id));
        await Promise.all([page.waitForResponse(r => r.url().endsWith('/templates') && r.request().method() === 'POST' && r.ok()), page.locator('#saveTemplate').click()]);
        await page.waitForFunction(() => document.querySelector('#templateSaveState').textContent === 'Đã lưu');
        await page.locator('#previewTemplate').click(); await page.waitForFunction(() => !document.querySelector('#labelPreview').hidden && document.querySelector('#labelPreview').naturalWidth > 0);
        await page.screenshot({ path: path.join(output, 'template-50x30-two-columns.png'), fullPage: true });
        const saved = (await request('/admin/label-printing/templates'))[0];
        assert.equal(saved.design.columns, 2); assert.equal(saved.design.widthMm, 50); assert.equal(saved.design.quantityMode, 'received');
        assert.equal(saved.design.layout, 'price-tag'); assert.equal(saved.design.barcodeFormat, 'AUTO');
        await page.locator('#templateFields [name=columns]').fill('3'); await page.locator('#previewTemplate').click();
        await page.waitForFunction(() => document.querySelector('#previewError').textContent.includes('vượt vùng in'));
        await page.locator('#templateFields [name=columns]').fill('2'); await page.locator('#saveTemplate').click();
        await page.waitForFunction(() => document.querySelector('#templateSaveState').textContent === 'Đã lưu');
        // A first-time receipt preview is read-only; queueing saves the chosen quantities.
        await page.goto(info.baseUrl + '/admin/stock-documents/' + info.receiptId);
        await page.locator('[data-label-add]').click();
        await page.locator('.label-print-popup [data-print-template]').first().waitFor();
        await page.keyboard.press('Escape');
        await page.locator('.label-print-popup').waitFor({state:'detached'});
        assert.equal((await request('/admin/label-printing/tasks')).length,0);
        await page.locator('[data-label-add]').click();
        await page.locator('[data-queue]').click();
        await page.waitForURL('**/admin/label-printing?task=*');
        await page.locator('#taskLines [data-quantity]').waitFor();
        assert.equal(await page.locator('#taskLines [data-quantity]').inputValue(),'48');
        await page.goto(info.baseUrl + '/admin/label-printing?receipt=' + info.receiptId);
        await Promise.all([page.waitForURL('**/admin/label-printing?task=*'), page.locator('#addReceipt').click()]);
        const adminPage = page;
        const employeeContext = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
        page = await employeeContext.newPage(); page.on('pageerror', e => errors.push(e.message));
        const settingsRequests = [];
        page.on('request', r => { if (/\/installed-printers|\/layouts\//.test(r.url())) settingsRequests.push(r.url()); });
        await login(page, info.employee);
        await page.goto(info.baseUrl + '/admin/label-printing');
        assert.equal(await page.locator('#layout-menu a[href="/admin/label-printing"]').count(), 1);
        assert.equal(await page.locator('a[href="/admin/label-printing-settings"]').count(), 0);
        assert.equal(await page.locator('#templateFields, #printerForm, #printTest').count(), 0);
        assert.deepEqual(await page.locator('.label-tabs [data-tab]').evaluateAll(xs => xs.map(x => x.dataset.tab)), ['quick', 'tasks', 'history']);
        const forbidden = await page.request.get(info.baseUrl + '/admin/label-printing-settings', { headers: { Accept: 'application/json' }, maxRedirects: 0 });
        assert.equal(forbidden.status(), 403);
        await page.locator('[data-tab=tasks]').click();
        await page.locator('[data-task]').first().click();
        await page.waitForSelector('#taskLines tr');
        assert.equal(await page.locator('#taskTemplate,#taskPrinter,#savePlan').count(), 0);
        assert.equal(await page.locator('#taskLines [data-quantity]').inputValue(), '48');
        assert.equal(await page.locator('#taskLines [data-selected]:checked').count(), 0);
        await page.locator('#taskLines [data-selected]').check();
        await page.locator('#taskLines [data-quantity]').fill('3');
        await page.locator(`#taskPrintEditor [data-preview-template="${saved.id}"]`).click();
        await page.locator('.label-preview-popup[open] img').waitFor();
        await page.locator('.label-preview-popup button').click();
        let firstReceiptRequest;
        await page.route('**/admin/label-printing/jobs', async route => {
            if (route.request().method() !== 'POST') return route.continue();
            firstReceiptRequest = route.request().postDataJSON(); await route.fetch(); await route.abort();
        });
        await page.locator(`#taskPrintEditor [data-print-template="${saved.id}"]`).click();
        await page.locator('.label-confirm-popup button[type=submit]').click();
        await page.locator('#taskPrintEditor [data-retry]').waitFor({state:'visible'});
        assert.equal(await page.locator('#taskLines [data-quantity]').isDisabled(),true);
        await page.unroute('**/admin/label-printing/jobs');
        const receiptRetry = page.waitForResponse(r => r.url().endsWith('/jobs') && r.request().method()==='POST' && r.ok());
        await page.locator('#taskPrintEditor [data-retry]').click();
        assert.deepEqual((await receiptRetry).request().postDataJSON(),firstReceiptRequest);
        await page.waitForFunction(() => document.querySelector('#taskHistory').textContent.includes('Chờ server in'));
        const jobs = await request('/admin/label-printing/jobs'); assert.equal(jobs.length, 1); assert.equal(jobs[0].quantity, 3);
        assert.equal(jobs[0].payload.items[0].product.price, 12345); assert.equal(jobs[0].payload.items[0].product.unit, 'Chai');
        assert.equal(jobs[0].payload.design.layout, 'price-tag'); assert.equal(jobs[0].payload.design.barcodeFormat, 'AUTO');
        await page.screenshot({ path: path.join(output, 'receipt-queued.png'), fullPage: true });
        await page.locator('[data-cancel-job]').first().click(); await page.locator('#dialogAccept').click();
        await page.waitForFunction(() => document.querySelector('#taskHistory').textContent.includes('Đã hủy'));
        await page.reload(); await page.waitForSelector('#taskLines tr');
        assert.equal(await page.locator('#taskLines [data-quantity]').inputValue(), '48');
        assert.equal(await page.locator('#taskLines [data-selected]:checked').count(), 0);
        await page.screenshot({ path: path.join(output, 'staff-print-workspace.png'), fullPage: true });
        await page.setViewportSize({ width: 390, height: 844 });
        await page.screenshot({ path: path.join(output, 'staff-print-mobile.png'), fullPage: true });
        assert.equal(await page.locator('#labelPrinting').evaluate(x => x.scrollWidth > x.clientWidth + 2), false);
        assert.deepEqual(settingsRequests, []);
        page = adminPage;
        await page.goto(info.baseUrl + '/admin/label-printing-settings');
        await page.waitForFunction(() => document.querySelector('[data-layout="price-tag"]').getAttribute('aria-pressed') === 'true');
        assert.equal(await page.locator('[data-layout="price-tag"]').getAttribute('aria-pressed'), 'true');
        await page.locator('[data-layout="framed"]').click();
        await page.locator('#templateFields [name=name]').fill('Khung tiệm · 50 × 30');
        await page.locator('#copyTemplate').click();
        await page.waitForFunction(() => document.querySelector('#templateSaveState').textContent === 'Đã lưu');
        const copies = await request('/admin/label-printing/templates'); assert.equal(copies.length, 2);
        assert.equal(copies.find(x => x.id === saved.id).design.layout, 'price-tag');
        assert.equal(copies.find(x => x.id !== saved.id).design.layout, 'framed');
        await page.locator('#newLargeTemplate').click();
        assert.equal(await page.locator('#templateFields [name=widthMm]').inputValue(), '50');
        assert.equal(await page.locator('#templateFields [name=heightMm]').inputValue(), '30');
        assert.equal(await page.locator('#templateFields [name=columns]').inputValue(), '1');
        assert.equal(await page.locator('#templateFields [name=fontSize]').inputValue(), '9');
        assert.equal(await page.locator('#templateFields [name=layout]').inputValue(), 'retail-large');
        await page.locator('#templatePrinter').selectOption(String(printers[0].id));
        await Promise.all([page.waitForResponse(r => r.url().endsWith('/templates') && r.request().method() === 'POST' && r.ok()), page.locator('#saveTemplate').click()]);
        await page.waitForFunction(() => document.querySelector('#templateSaveState').textContent === 'Đã lưu');
        const withLarge = await request('/admin/label-printing/templates');
        assert.equal(withLarge.length, 3);
        for (const original of copies) assert.deepEqual(withLarge.find(x => x.id === original.id).design, original.design);
        const large = withLarge.find(x => x.design.layout === 'retail-large');
        assert.equal(large.design.widthMm, 50); assert.equal(large.design.heightMm, 30);
        await page.reload();
        await page.locator(`[data-template="${large.id}"]`).click();
        await page.waitForFunction(() => document.querySelector('#labelPreview').complete && document.querySelector('#labelPreview').naturalWidth > 0 && !document.querySelector('#labelPreview').hidden);
        assert.equal(await page.locator('#templateFields [name=layout]').inputValue(), 'retail-large');
        const previewResponse = await page.request.get(info.baseUrl + '/admin/label-printing/layouts/retail-large/preview');
        assert.equal(previewResponse.status(), 200);
        fs.writeFileSync(path.join(output, 'retail-large-50x30.png'), await previewResponse.body());
        await page.locator('#labelPreview').scrollIntoViewIfNeeded();
        await page.screenshot({ path: path.join(output, 'retail-large-editor.png') });
        const popupPage = await context.newPage(); popupPage.on('pageerror', e => errors.push(e.message));
        await popupPage.goto(info.baseUrl + '/admin/stock-documents/' + info.receiptId);
        let nativeDialogs = 0; popupPage.on('dialog', async d => { nativeDialogs++; await d.dismiss(); });
        await popupPage.locator('[data-label-add]').click();
        await popupPage.locator('.label-print-popup[open] [data-print-template]').first().waitFor();
        await popupPage.screenshot({path:path.join(output,'receipt-print-popup.png'),fullPage:true});
        await popupPage.keyboard.press('Escape');
        await popupPage.locator('.label-print-popup').waitFor({state:'detached'});
        await popupPage.evaluate(id => window.GaoLabels.afterApproval(id, false), info.receiptId);
        assert.equal(await popupPage.locator('.label-print-popup[open]').count(), 0);
        await popupPage.evaluate(id => window.GaoLabels.afterApproval(id, true), info.receiptId);
        await popupPage.locator('[data-label-add]').click();
        await popupPage.locator('#popupTaskLines [data-quantity]').waitFor();
        assert.equal(await popupPage.locator('#popupTaskLines [data-selected]:checked').count(), 0);
        await popupPage.locator('[data-quantity-mode=one]').click();
        assert.equal(await popupPage.locator('#popupTaskLines [data-quantity]').inputValue(),'1');
        await popupPage.locator('#popupTaskLines [data-quantity]').fill('5');
        await popupPage.setViewportSize({width:390,height:844});
        await popupPage.screenshot({path:path.join(output,'receipt-print-popup-mobile.png'),fullPage:true});
        await popupPage.locator('[data-queue]').click();
        await popupPage.waitForURL('**/admin/label-printing?task=*');
        await popupPage.locator('#taskLines [data-quantity]').waitFor();
        assert.equal(await popupPage.locator('#taskLines [data-selected]:checked').count(), 0);
        assert.equal(nativeDialogs,0); await popupPage.close();
        page = await employeeContext.newPage(); page.on('pageerror', e => errors.push(e.message));
        await page.goto(info.baseUrl + '/admin/label-printing');
        await page.locator('#quickSearch').fill('8938505974194');
        await page.locator('#quickSearch').press('Enter');
        await page.locator('#quickLines [data-quick-line]').waitFor();
        assert.equal(await page.locator('#quickLines input').inputValue(), '1');
        await page.locator('#quickLines input').fill('2');
        await Promise.all([page.waitForResponse(r => r.url().endsWith('/products/refresh') && r.ok()), page.locator('#quickRefresh').click()]);
        await page.waitForFunction(() => !document.getElementById('quickFields').disabled);
        assert.equal(await page.locator('#quickTemplate,#quickPrinter').count(), 0);
        await page.locator(`#quickPrintChoices [data-preview-template="${large.id}"]`).click();
        await page.locator('#labelDialog[open] img').waitFor();
        await page.locator('#dialogClose').click();
        await page.screenshot({ path: path.join(output, 'quick-print-desktop.png'), fullPage: true });
        // Lose the response AFTER the server accepts it; retry must not enqueue twice.
        let firstRequest;
        await page.route('**/admin/label-printing/jobs', async route => {
            if (route.request().method() !== 'POST') return route.continue();
            firstRequest = route.request().postDataJSON();
            await route.fetch(); await route.abort();
        });
        await page.locator(`#quickPrintChoices [data-print-template="${large.id}"]`).click();
        await page.locator('.label-confirm-popup button[type=submit]').click();
        await page.waitForFunction(() => document.querySelector('#labelMessage').textContent.includes('cùng mã yêu cầu'));
        assert.equal(await page.locator('#quickSearch').isDisabled(), true);
        await page.unroute('**/admin/label-printing/jobs');
        const retryResponse = page.waitForResponse(r => r.url().endsWith('/jobs') && r.request().method() === 'POST' && r.ok());
        await page.locator('#quickPrint').click();
        const retried = await retryResponse;
        assert.equal(retried.request().postDataJSON().requestId, firstRequest.requestId);
        await page.waitForFunction(() => document.querySelector('#allHistory').textContent.includes('In nhanh sản phẩm'));
        const quickJobs = await request('/admin/label-printing/jobs');
        assert.equal(quickJobs.length, 2);
        const quickJob = quickJobs.find(x => !x.taskId);
        assert.equal(quickJob.quantity, 2); assert.equal(quickJob.payload.items[0].product.price, 12345);
        assert.ok(quickJob.payload.items[0].product.unitId > 0);
        assert.equal(await page.locator('#quickLines [data-quick-line]').count(), 0);
        await page.locator('[data-tab=quick]').click();
        await page.setViewportSize({ width: 390, height: 844 });
        await page.locator('#quickSearch').fill('8938505974194'); await page.locator('#quickSearch').press('Enter');
        await page.locator('#quickLines [data-quick-line]').waitFor();
        await page.waitForFunction(() => !document.getElementById('quickPrint').disabled);
        await page.screenshot({ path: path.join(output, 'quick-print-mobile.png'), fullPage: true });
        assert.equal(await page.locator('#labelPrinting').evaluate(x => x.scrollWidth > x.clientWidth + 2), false);
        const quickOptions = await request('/admin/label-printing/products?q=8938505974194');
        const shortcutPage = await context.newPage();
        await shortcutPage.goto(info.baseUrl + '/Admin/Product');
        const shortcut = shortcutPage.locator(`a[href*="tab=quick"][href*="productId=${quickOptions[0].productId}"]`).first();
        await shortcut.waitFor(); await shortcut.click();
        await shortcutPage.locator('#quickLines [data-quick-line]').waitFor();
        assert.equal(await shortcutPage.locator('#quickLines input').inputValue(), '1');
        await shortcutPage.close();
        page = adminPage;
        await page.setViewportSize({ width: 390, height: 844 });
        await page.locator('#layoutGallery').scrollIntoViewIfNeeded();
        await page.waitForFunction(() => [...document.querySelectorAll('#layoutGallery img')].every(x => x.complete && x.naturalWidth > 0));
        await page.screenshot({ path: path.join(output, 'templates-mobile.png'), fullPage: true });
        const overflow = await page.locator('#labelPrinting').evaluate(x => x.scrollWidth > x.clientWidth + 2); assert.equal(overflow, false);
        assert.deepEqual(errors, []);
        console.log('PASS: admin/staff permissions, receipt queue/cancel/defaults, five layouts, 50x30 preset, staff quick scan/preview/print, uncertain submission retry without duplication, AUTO and responsive UI.');
    } catch (error) { await page.screenshot({ path: path.join(output, 'failure.png'), fullPage: true }); throw error; }
    finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
