'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
(async () => {
    const info = JSON.parse(await new Promise(resolve => { let text = ''; process.stdin.on('data', value => text += value); process.stdin.on('end', () => resolve(text)); }));
    const output = path.resolve('TestResults/label-progress'); fs.mkdirSync(output, { recursive: true });
    const browser = await chromium.launch({ channel: 'chrome', headless: true });
    const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
    const page = await context.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.route('**/uploads/test-label-product.svg', route => route.fulfill({ contentType: 'image/svg+xml', body: '<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180"><rect width="180" height="180" fill="#f4f7ed"/><path d="M58 38h64v112H58z" fill="#f7fcff" stroke="#90b7d1" stroke-width="3"/><path d="M58 38l15-20h34l15 20" fill="#5286bc"/><path d="M58 90q32-38 64 0v42H58z" fill="#6da678"/><text x="90" y="72" text-anchor="middle" font-size="19" fill="#235987">MILK</text></svg>' }));
    const request = (suffix, method = 'GET', body) => page.evaluate(async ({ suffix, method, body }) => {
        const response = await fetch('/admin/label-printing/' + suffix, { method, headers: { 'Content-Type': 'application/json', RequestVerificationToken: document.querySelector('[name="__RequestVerificationToken"]').value }, body: body === undefined ? undefined : JSON.stringify(body) });
        const text = await response.text(); if (!response.ok) throw new Error(response.status + ': ' + text); return text ? JSON.parse(text) : null;
    }, { suffix, method, body });
    try {
        await page.goto(info.baseUrl + '/admin/account/login');
        await page.locator('[name=UserName]').fill(info.user); await page.locator('[name=Password]').fill(info.password);
        if (await page.locator('select[name=SelectedTerminalId]').count()) await page.locator('select[name=SelectedTerminalId]').selectOption(String(info.terminalId));
        await Promise.all([page.waitForURL(url => !url.pathname.endsWith('/login')), page.locator('#loginForm button[type=submit]').click()]);
        await page.goto(info.baseUrl + '/admin/label-printing');
        const printer = await request('printers', 'POST', { name: 'Xprinter · Quầy kho', windowsPrinterName: 'FAKE TRANSPORT ONLY', dpi: 203, printableWidthMm: 108, enabled: true });
        const template = await request('templates', 'POST', { design: { name: 'Tem siêu thị 50 × 30', printerId: printer.id, layout: 'retail-large', widthMm: 50, heightMm: 30, columns: 1, fontSize: 9, quantityMode: 'one' } });
        const added = await request('receipts/' + info.receiptId, 'POST');
        await page.goto(info.baseUrl + '/admin/label-printing?task=' + added.id);
        await page.locator('#taskLines tr').first().waitFor();
        assert.equal(await page.locator('#taskLines [data-selected]:checked').count(), 0);
        assert.match(await page.locator('#taskTitle').textContent(), /Nguyễn/);
        await page.locator('[data-quantity-mode=received]').click();
        assert.equal(await page.locator('#taskLines [data-selected]:checked').count(), 0);
        await page.locator('#taskLines [data-selected]').first().check();
        await page.locator('#taskLines [data-quantity]').first().fill('2');
        await page.locator('#taskPrintEditor [data-print-template]').first().click();
        await page.locator('.label-confirm-popup[open]').waitFor();
        assert.match(await page.locator('.label-confirm-printer').textContent(), /Xprinter · Quầy kho/);
        assert.match(await page.locator('.label-confirm-metrics').textContent(), /2/);
        assert.equal((await request('jobs')).length, 0); // Nothing is sent before confirmation.
        await page.screenshot({ path: path.join(output, 'confirm-print.png'), fullPage: false });
        await page.keyboard.press('Escape');
        assert.equal((await request('jobs')).length, 0);
        await page.locator('#taskPrintEditor [data-print-template]').first().click();
        await page.locator('.label-confirm-popup button[type=submit]').click();
        await page.waitForFunction(() => document.querySelector('#taskTotals').textContent.includes('1 / 2'));
        assert.equal(await page.locator('#taskLines [data-selected]:checked').count(), 0);
        assert.equal((await page.locator('#taskLines tr').first().locator('td').nth(4).textContent()).trim(), '2');
        await page.locator('[data-skip-rest]').click();
        await page.locator('.label-confirm-popup [name=reason]').selectOption({ label: 'Khác' });
        await page.locator('.label-confirm-popup button[type=submit]').click();
        assert.equal(await page.locator('.label-confirm-popup[open]').count(), 1);
        await page.locator('.label-confirm-popup [name=note]').fill('Sản phẩm đã có tem nhà cung cấp');
        await page.locator('.label-confirm-popup button[type=submit]').click();
        await page.waitForFunction(() => document.querySelector('#taskTotals').textContent.includes('2 / 2'));
        let task = await request('tasks/' + added.id);
        assert.deepEqual(task.progress, { total: 2, handled: 1, skipped: 1, pending: 0 });
        const completedAt = task.completedAtUtc;
        await page.locator('#taskState').selectOption('completed');
        await page.locator('#taskSearch').fill('nguyen');
        await page.waitForFunction(() => document.querySelectorAll('#labelTaskList [data-task]').length === 1);
        await page.screenshot({ path: path.join(output, 'receipt-workspace.png'), fullPage: true });
        await page.locator('#taskLines [data-selected]').first().check();
        await page.locator('#taskPrintEditor [data-print-template]').first().click();
        assert.match(await page.locator('.label-confirm-popup').textContent(), /0 sản phẩm xử lý lần đầu · 1 sản phẩm in lại/);
        await page.locator('.label-confirm-popup button[type=submit]').click();
        await page.waitForFunction(() => document.querySelectorAll('#taskHistory .label-job').length === 2 && document.querySelectorAll('#taskHistory .label-job')[0].textContent.includes('Đã gửi in'));
        task = await request('tasks/' + added.id);
        assert.equal(task.completedAtUtc, completedAt); assert.equal(task.progress.handled, 1); assert.equal(task.progress.skipped, 1);
        await page.locator('[data-restore]').click();
        await page.locator('.label-confirm-popup button[type=submit]').click();
        await page.waitForFunction(() => document.querySelector('#taskTotals').textContent.includes('1 / 2'));
        assert.match(await page.locator('#taskResolutionHistory').textContent(), /Khôi phục/);
        await page.locator('[data-select=pending]').click();
        assert.equal(await page.locator('#taskLines [data-selected]:checked').count(), 1);
        assert.equal(await page.locator('#taskLines [data-selected]').first().isChecked(), false);
        await page.reload(); await page.locator('#taskLines tr').first().waitFor();
        assert.equal(await page.locator('#taskLines [data-selected]:checked').count(), 0);
        await page.locator('[data-image]').first().hover();
        assert.equal(await page.locator('.label-image-zoom').count(), 1);
        await page.mouse.move(0, 0);
        await page.setViewportSize({ width: 390, height: 844 });
        await page.screenshot({ path: path.join(output, 'mobile-workspace.png'), fullPage: true });
        assert.equal(await page.locator('#labelPrinting').evaluate(x => x.scrollWidth > x.clientWidth + 2), false);
        assert.equal(await page.locator('.label-receipt-table').evaluate(x => x.scrollWidth > x.parentElement.clientWidth + 2), false);
        assert.equal(await page.locator('.label-tasks-table').evaluate(x => x.scrollWidth > x.parentElement.clientWidth + 2), false);
        assert.deepEqual(errors, []);
        console.log('PASS: unchecked defaults, quantity modes, one confirmation, real dispatcher progress, reprint unchanged, skip/restore audit, accent search, responsive view.');
    } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exit(1); });
