const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
(async()=>{
  const info=JSON.parse(await new Promise(resolve=>{let s='';process.stdin.on('data',x=>s+=x);process.stdin.on('end',()=>resolve(s));}));
  const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:1480,height:1080},reducedMotion:'reduce'}),page=await context.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  const output=path.resolve('TestResults/management-reports');fs.mkdirSync(output,{recursive:true});
  const loaded=async()=>{await page.waitForFunction(()=>document.querySelector('[data-management-report]')?.getAttribute('aria-busy')==='false');assert.equal(await page.locator('[data-report-error]').isVisible(),false,await page.locator('[data-report-error]').innerText());assert.ok(await page.locator('[data-report-results]').isVisible());};
  const go=async section=>{await page.goto(info.baseUrl+'/admin/reports/'+section);await loaded();};
  try{
    await page.goto(info.baseUrl+'/admin/account/login');await page.locator('[name=UserName]').fill(info.user);await page.locator('[name=Password]').fill(info.password);await page.locator('[name=SelectedTerminalId]').selectOption(String(info.terminalId));await Promise.all([page.waitForURL(u=>!u.pathname.endsWith('/login')),page.locator('#loginForm button[type=submit]').click()]);
    await go('overview');assert.equal(await page.locator('.mr-kpi').count(),4);await page.waitForSelector('[data-chart=area] .apexcharts-svg');await page.waitForSelector('[data-chart=donut] .apexcharts-svg');await page.waitForSelector('[data-chart=treemap] .apexcharts-svg');assert.ok(await page.locator('.mr-waterfall').isVisible());
    assert.match(await page.locator('[data-report-kpis]').innerText(),/720/);await page.screenshot({path:path.join(output,'overview-desktop.png'),fullPage:true});
    await page.locator('[name=preset]').selectOption('today');await page.locator('[data-report-filters] button[type=submit]').click();await loaded();
    await page.locator('[data-report-nav=profit]').click();await loaded();assert.equal(await page.locator('[name=fromDate]').inputValue(),info.day);assert.equal(await page.locator('[name=toDate]').inputValue(),info.day);await page.waitForSelector('[data-chart=combo] .apexcharts-svg');
    assert.match(await page.locator('[data-profit-detail-table]').last().innerText(),/720/);assert.match(await page.locator('[data-profit-detail-table]').last().innerText(),/180/);await page.screenshot({path:path.join(output,'profit-desktop.png'),fullPage:true});
    const response=await context.request.get(info.baseUrl+await page.locator('[data-export]').getAttribute('href'));assert.ok(response.ok());assert.match(await response.text(),/Doanh thu thuần/);
    for(const section of ['groups','customers','products','categories']){await go(section);if(section==='groups')await page.waitForSelector('[data-chart=stacked] .apexcharts-svg');if(section==='customers')await page.waitForSelector('[data-chart=scatter] .apexcharts-svg');await page.screenshot({path:path.join(output,section+'-desktop.png'),fullPage:true});assert.match(await page.locator('[data-report-panels]').innerText(),/Gạo|Khách|R2 Category|Nguyễn|Hiệu quả|hiệu quả/);}
    await page.locator('[data-dimension-filter] [name=search]').fill('NO_MATCH');await page.locator('[data-dimension-filter] button[type=submit]').click();assert.match(await page.locator('[data-report-panels]').innerText(),/Không có dữ liệu/);
    await go('expenses');await page.locator('[data-expense-new]').click();const f=page.locator('[data-expense-form]');assert.ok(await page.locator('[data-expense-dialog]').isVisible());await f.locator('[name=name]').fill('Chi phí kiểm thử trình duyệt');await f.locator('[name=amount]').fill('10');await f.locator('[data-expense-save]').click();await page.waitForFunction(()=>!document.querySelector('[data-expense-dialog]').open);await loaded();
    let row=page.locator('.mr-table tbody tr').filter({hasText:'Chi phí kiểm thử trình duyệt'});assert.match(await row.innerText(),/Nháp/);
    await row.locator('[data-expense-edit]').click();await f.locator('[name=amount]').fill('12');await f.locator('[data-expense-save]').click();await page.waitForFunction(()=>!document.querySelector('[data-expense-dialog]').open);await loaded();
    await row.locator('[data-expense-confirm]').click();await page.locator('[data-action-submit]').click();await page.waitForFunction(()=>!document.querySelector('[data-expense-action-dialog]').open);await loaded();assert.match(await row.innerText(),/Đã ghi nhận/);assert.match(await page.locator('[data-report-kpis]').innerText(),/192/);await page.screenshot({path:path.join(output,'expenses-desktop.png'),fullPage:true});
    await row.locator('[data-expense-void]').click();await page.locator('[data-expense-action-form] [name=reason]').fill('Khoản thử đã kiểm tra');await page.locator('[data-action-submit]').click();await page.waitForFunction(()=>!document.querySelector('[data-expense-action-dialog]').open);await loaded();assert.match(await row.innerText(),/Đã hủy/);assert.match(await page.locator('[data-report-kpis]').innerText(),/180/);
    await page.setViewportSize({width:390,height:844});for(const section of ['overview','profit','expenses']){await go(section);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'Mobile overflow '+section);await page.screenshot({path:path.join(output,section+'-mobile.png'),fullPage:true});}
    await page.locator('[data-report-menu]').click();await page.waitForFunction(()=>document.documentElement.classList.contains('layout-menu-expanded'));await page.locator('.layout-overlay').click({position:{x:380,y:100}});await page.waitForFunction(()=>!document.documentElement.classList.contains('layout-menu-expanded'));
    await page.setViewportSize({width:1480,height:1080});await go('overview');await page.evaluate(()=>document.documentElement.classList.add('dark-style'));await page.waitForSelector('[data-chart=area] .apexcharts-svg');await page.screenshot({path:path.join(output,'overview-dark.png'),fullPage:true});
    await page.route('**/admin/reports/management/data?**',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'Báo cáo đang bận'})}));await page.locator('[data-report-refresh]').click();await page.waitForSelector('[data-report-error]:visible');assert.equal(await page.locator('[data-report-results]').isVisible(),false);await page.unroute('**/admin/reports/management/data?**');await page.locator('[data-report-retry]').click();await loaded();
    await page.locator('[name=fromDate]').fill('2001-01-01');await page.locator('[name=toDate]').fill('2001-01-02');await page.locator('[data-report-filters] button[type=submit]').click();await loaded();assert.match(await page.locator('[data-report-kpis]').innerText(),/0 ₫/);
    assert.deepEqual(errors,[]);console.log('PASS: seven report pages, all charts, shared dates, CSV, draft/edit/confirm/void, totals, mobile, dark theme, error/retry and empty range.');
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
