'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
(async () => {
    const info = JSON.parse(await new Promise(resolve => { let s = ''; process.stdin.on('data', x => s += x); process.stdin.on('end', () => resolve(s)); }));
    const output = path.resolve('TestResults/pos-scan-feedback'); fs.mkdirSync(output, { recursive: true });
    const browser = await chromium.launch({ channel: 'chrome', headless: true });
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    const page = await context.newPage(), errors = [];
    page.setDefaultTimeout(20000); page.on('pageerror', error => errors.push(error.message));
    const state = () => page.evaluate(() => posApp.state.business.currentDraft);
    const count = () => page.locator('#posScanHistoryList li').count();
    async function scan(code, amount = 1) {
        const before = await count() ? await page.locator('#posScanHistoryList li').first().getAttribute('data-scan-receipt') : '';
        await page.locator('#txtBarcode').click();
        await page.locator('#txtBarcode').fill(amount === 1 ? code : amount + '+' + code);
        await page.locator('#txtBarcode').press('Enter');
        await page.waitForFunction(old => document.querySelector('#posScanHistoryList li')?.dataset.scanReceipt && document.querySelector('#posScanHistoryList li').dataset.scanReceipt !== old, before);
        await page.waitForFunction(() => !posApp.state.network.busyScopes.size);
        assert.equal(await page.locator('#txtBarcode').inputValue(), '');
        assert.equal(await page.locator('#barcodeAutocomplete').isVisible(), false, 'Old autocomplete must close after every scan');
        assert.equal(await page.locator('.modal.show').count(), 0, 'No automatic success popup');
        assert.equal(await page.locator('#btnOpenPayment').isDisabled(), false, 'Payment must unlock immediately');
    }
    async function latest(name, unit, before, after) {
        assert.equal(await page.locator('#posScanName').innerText(), name);
        assert.equal(await page.locator('#posScanTransition').innerText(), `${before} → ${after} ${unit}`);
        const row = page.locator('#currentDraftBody tr[data-line-id]').first();
        assert.ok((await row.locator('.pos-line-name').innerText()).includes(name), 'Confirmed product must be the first cart row');
        assert.equal(Number(await row.locator('.qty-input').inputValue()), after);
        assert.match(await row.getAttribute('class'), /pos-scan-received/);
    }
    async function history(direction) {
        await page.locator('#posScanHistoryOpen').click();
        await page.locator('#posScanHistory.show').waitFor();
        const box = await page.locator('#posScanHistory').boundingBox(), viewport = page.viewportSize();
        assert.ok(direction === 'bottom' ? box.y > 60 && Math.abs(box.x) < 2 && Math.abs(box.width - viewport.width) < 2 : box.x > viewport.width / 2, direction + ' history geometry');
        const cartId = (await state()).orderId;
        await page.keyboard.press('F2'); await page.keyboard.press('F3');
        assert.equal(await page.locator('.modal.show').count(), 0, 'History must own keyboard focus');
        assert.equal((await state()).orderId, cartId);
        await page.screenshot({ path: path.join(output, 'history-' + direction + '.png') });
        await page.locator('#posScanHistory .btn-close').click();
        await page.locator('#posScanHistory').waitFor({ state: 'hidden' });
    }
    try {
        await page.route('**/uploads/products/scan-test*', route => route.fulfill({ contentType:'image/svg+xml', body:'<svg xmlns="http://www.w3.org/2000/svg" width="120" height="160"><rect x="30" y="5" width="60" height="150" rx="14" fill="#267453"/><rect x="34" y="48" width="52" height="65" fill="#e4e8dd"/><text x="60" y="80" text-anchor="middle" font-size="18" font-family="Arial" fill="#267453">KEN</text></svg>' }));
        await page.route('**/uploads/products/scan-water-test*', route => route.fulfill({ contentType:'image/svg+xml', body:'<svg xmlns="http://www.w3.org/2000/svg" width="120" height="160"><rect x="45" y="5" width="30" height="20" rx="4" fill="#226eaa"/><rect x="32" y="24" width="56" height="132" rx="18" fill="#bddff3"/><rect x="32" y="60" width="56" height="50" fill="#2784b6"/><text x="60" y="90" text-anchor="middle" font-size="14" font-family="Arial" fill="white">WATER</text></svg>' }));
        await page.goto(info.baseUrl + '/admin/account/login');
        await page.locator('[name=UserName]').fill(info.user); await page.locator('[name=Password]').fill(info.password);
        if (await page.locator('select[name=SelectedTerminalId]').count()) await page.locator('select[name=SelectedTerminalId]').selectOption(String(info.terminalId));
        await Promise.all([page.waitForURL(url => !url.pathname.endsWith('/login')), page.locator('#loginForm button[type=submit]').click()]);
        await page.goto(info.baseUrl + '/admin/pos');
        await page.waitForFunction(() => window.posApp?.state.business.currentDraft && window.PosOffline?.status().ready);
        await page.evaluate(() => { window.__scanSounds = 0; window.Audio = function () { window.__scanSounds++; }; });
        await page.route('**/admin/pos/cart/current/scan', async route => { await new Promise(resolve => setTimeout(resolve,600)); await route.continue(); });
        const first = scan('2099900000001');
        await page.locator('#posScanFeedback[data-state=saving]').waitFor();
        assert.equal(await count(), 0, 'No history before acknowledged save');
        await first; await page.unroute('**/admin/pos/cart/current/scan');
        await latest('Bia Ken bạc 330 ml', 'Lon', 0, 1);
        await page.locator('#posScanImage:not([hidden])').waitFor();
        await page.locator('#posScanPhoto').click(); await page.locator('#imagePreviewModal.show').waitFor();
        assert.equal(await page.locator('#imagePreviewEl').getAttribute('alt'),'Bia Ken bạc 330 ml');
        await page.locator('#imagePreviewModal [data-bs-dismiss="modal"]').first().click();
        await page.locator('#imagePreviewModal').waitFor({ state:'hidden' });
        await scan('2099900000003'); await latest('Nước suối tinh khiết 500 ml', 'Lon', 0, 1);
        assert.match(await page.locator('#posScanImage').getAttribute('src'),/scan-water-test/);
        await scan('2099900000001'); await latest('Bia Ken bạc 330 ml', 'Lon', 1, 2);
        assert.match(await page.locator('#posScanImage').getAttribute('src'),/scan-test/);
        await scan('2099900000002'); await latest('Bia Ken bạc 330 ml', 'Lốc', 0, 1);
        assert.match(await page.locator('#posScanMeta').innerText(), /Lốc \(6 Lon\)/);
        assert.equal((await state()).lines.find(x => x.sellingUnitName === 'Lon' && x.variantId === info.variantId).quantity, 2);
        await scan('2099900000001', 3); await latest('Bia Ken bạc 330 ml', 'Lon', 2, 5);
        await page.waitForFunction(() => !document.querySelector('.pos-scan-received'));
        assert.equal(await page.locator('#posScanLast').isVisible(), true, 'Receipt persists after the 1.5 second flash');
        const scanBox = await page.locator('#txtBarcode').boundingBox(), card = await page.locator('#posScanFeedback').boundingBox();
        assert.ok(card.y >= scanBox.y + scanBox.height, 'Receipt belongs under the scanner');
        await page.screenshot({ path: path.join(output, 'desktop.png') });
        await history('right');
        assert.equal(await page.evaluate(() => window.__scanSounds),0,'Scans must be silent');
        console.log('PASS exact barcode A/B/A, quantity prefix, separate pack, positive delta, first row, delayed save, persistent card and desktop history');
        const beforeReload = await page.locator('#posScanHistoryList').innerText();
        await page.reload(); await page.waitForFunction(() => !!window.posApp?.state.business.currentDraft);
        await page.locator('#posScanLast').waitFor();
        assert.equal(await page.locator('#posScanHistoryList').innerText(), beforeReload);
        assert.equal(await count(), 5);
        const line = (await state()).lines.find(x => x.variantId === info.variantId && x.sellingUnitName === 'Lon');
        await page.evaluate(async id => posApp.modules.posOrder.updateLineQty(id, 4), line.lineId);
        assert.equal(await count(), 5, 'Quantity edit is not another scan');
        assert.equal(await page.locator('#posScanTransition').innerText(), '2 → 5 Lon', 'Historical receipt must remain truthful after an edit');
        assert.equal(await page.locator('#posScanCurrent').innerText(), 'Hiện trong giỏ: 4 Lon');
        for (const width of [390,320]) {
            await page.setViewportSize({ width, height:780 });
            await page.locator('#posScanLast').waitFor();
            await history('bottom');
            const position = await page.evaluate(() => { const c = document.querySelector('.pos-cart-scroll'); c.scrollTop = c.scrollHeight; return { y:scrollY, cart:c.scrollTop }; });
            await scan('2099900000003');
            const after = await page.evaluate(() => { const c = document.querySelector('.pos-cart-scroll'); return { y:scrollY, cart:c.scrollTop, max:c.scrollHeight-c.clientHeight }; });
            assert.equal(after.y, position.y, 'Scan must not scroll the whole page');
            assert.ok(Math.abs(after.cart-Math.min(position.cart,after.max)) < 2, 'Reorder must preserve cart scroll, clamped only when its content becomes shorter: ' + JSON.stringify({position,after}));
            console.log('PASS mobile scan scroll', JSON.stringify({width,position,after}));
            const geometry = await page.evaluate(() => ({ width:innerWidth, right:document.querySelector('#posScanFeedback').getBoundingClientRect().right, body:document.documentElement.scrollWidth }));
            assert.ok(geometry.right <= width && geometry.body <= width, 'No horizontal overflow');
            await page.screenshot({ path:path.join(output,'mobile-' + width + '.png') });
        }
        // Expiring feedback must preserve a position the user chose after the scan.
        const beforeExpiry = await page.evaluate(() => { const c = document.querySelector('.pos-cart-scroll'); c.scrollTop = c.scrollTop / 2; return { y:scrollY, cart:c.scrollTop }; });
        await page.waitForFunction(() => !document.querySelector('.pos-scan-badge'));
        const expired = await page.evaluate(() => { const c = document.querySelector('.pos-cart-scroll'); return { y:scrollY, cart:c.scrollTop, max:c.scrollHeight-c.clientHeight }; });
        assert.equal(expired.y, beforeExpiry.y, 'Expiring feedback must not scroll the whole page');
        assert.ok(Math.abs(expired.cart-Math.min(beforeExpiry.cart,expired.max)) < 2, 'Expiring feedback must preserve the current user scroll, clamped only to the final range: ' + JSON.stringify({beforeExpiry,expired}));
        console.log('PASS feedback expiry preserves user scroll', JSON.stringify({beforeExpiry,expired}));
        console.log('PASS reload, history unchanged after quantity editing, 320/390 mobile sheet and stable scroll');
        const n = await count();
        let rejectedRequests = 0;
        await page.route('**/admin/pos/cart/current/scan', route => { rejectedRequests++; return route.fulfill({ status:400, contentType:'application/json', body:JSON.stringify({ message:'Không tìm thấy sản phẩm theo barcode.' }) }); });
        await page.locator('#txtBarcode').fill('2099900000001'); await page.locator('#txtBarcode').press('Enter');
        await page.locator('#posScanFeedback[data-state=error]').waitFor();
        assert.equal(await count(), n); assert.equal(await page.locator('#posScanLast').isVisible(), true);
        await page.locator('#posScanGuard[open]').waitFor();
        assert.equal(await page.locator('#posScanGuardCode').innerText(), '2099900000001');
        await page.keyboard.type('2099900000003'); await page.keyboard.press('Enter');
        await page.keyboard.press('Enter'); // A second scanner terminator must also be swallowed.
        await page.keyboard.press('Escape'); await page.keyboard.press('F2');
        assert.equal(await page.locator('#posScanGuard').isVisible(), true);
        assert.equal((await page.evaluate(() => posApp.modules.posBarcode.scanCurrentCart())).status, 'blocked');
        assert.equal((await page.evaluate(id => posApp.modules.posBarcode.addVariantToCurrentCart(id, 1), info.variantId)).status, 'blocked');
        assert.equal(rejectedRequests, 1); assert.equal(await count(), n);
        await page.screenshot({ path:path.join(output, 'missing-barcode-mobile.png') });
        const guardGeometry = await page.locator('#posScanGuardConfirm').boundingBox();
        assert.ok(guardGeometry.x >= 0 && guardGeometry.y + guardGeometry.height <= 780);
        await page.waitForTimeout(550); await page.keyboard.press('Enter');
        await page.locator('#posScanGuard').waitFor({ state:'hidden' });
        assert.equal(await page.locator('#txtBarcode').inputValue(), '');
        assert.equal(await page.locator('#txtBarcode').evaluate(node => document.activeElement === node), true);
        await page.unroute('**/admin/pos/cart/current/scan');
        await page.locator('#posScanRetry').click(); await page.waitForFunction(n => document.querySelectorAll('#posScanHistoryList li').length === n+1,n);
        assert.equal(await count(), n+1);
        // Server commits, response is lost: the offline journal retries the same command.
        let dropped = false;
        await page.route('**/admin/pos/cart/current/scan', async route => {
            if (!dropped) { dropped = true; await route.fetch(); await route.abort('failed'); } else await route.continue();
        });
        const beforeLost = (await state()).lines.find(x => x.variantId === info.variantId && x.sellingUnitName === 'Lon').quantity;
        await scan('2099900000001');
        assert.match(await page.locator('#posScanStatus').innerText(), /Đã lưu tại quầy/);
        const countAfterLost = await count();
        await page.unroute('**/admin/pos/cart/current/scan');
        await page.evaluate(() => PosOffline.sync());
        await page.waitForFunction(() => PosOffline.status().pending === 0);
        await page.evaluate(() => posApp.loadScreen());
        assert.equal(await count(), countAfterLost, 'Journal replay must not duplicate history');
        assert.equal((await state()).lines.find(x => x.variantId === info.variantId && x.sellingUnitName === 'Lon').quantity, beforeLost+1);
        for (let i=0;i<4;i++) await scan('2099900000001');
        assert.equal(await count(),10);
        assert.equal(new Set(await page.locator('#posScanHistoryList li').evaluateAll(nodes => nodes.map(n=>n.dataset.scanReceipt))).size,10);
        console.log('PASS rejected save, explicit retry, lost server reply, journal replay without double quantity or history, last ten individual scans');
        const previousPack = (await state()).lines.find(x => x.sellingUnitName === 'Lốc').quantity;
        await page.setViewportSize({width:1440,height:1000});
        await page.locator('#txtBarcode').click(); await page.locator('#txtBarcode').fill('2+Bia Ken');
        await page.locator('#barcodeAutocomplete [data-autocomplete-kind="parent"]').waitFor();
        await page.locator('#txtBarcode').press('ArrowDown'); await page.locator('#txtBarcode').press('ArrowRight');
        const manualStamp = await page.locator('#posScanHistoryList li').first().getAttribute('data-scan-receipt');
        await page.locator(`#barcodeAutocomplete [data-product-unit-conversion-id="${info.packId}"] .pos-ac-title`).click();
        await page.waitForFunction(id => document.querySelector('#posScanHistoryList li').dataset.scanReceipt !== id,manualStamp);
        await latest('Bia Ken bạc 330 ml','Lốc',previousPack,previousPack+2);
        const previousCan = (await state()).lines.find(x => x.variantId === info.variantId && x.sellingUnitName === 'Lon').quantity;
        assert.equal((await page.evaluate(id => posApp.modules.posBarcode.addVariantToCurrentCart(id,1),info.variantId)).ok,true);
        await latest('Bia Ken bạc 330 ml','Lon',previousCan,previousCan+1);
        console.log('PASS manual product and explicit unit selections use the same confirmed history');
        const oldCart = (await state()).orderId;
        const held = await page.evaluate(() => posApp.modules.posOrder.holdCurrentCart());
        assert.equal(held.ok,true,JSON.stringify(held));
        await page.waitForFunction(id => posApp.state.business.currentDraft.orderId !== id,oldCart);
        assert.notEqual((await state()).orderId,oldCart); assert.equal(await count(),0); assert.equal(await page.locator('#posScanLast').isVisible(),false);
        const onlineCart = (await state()).orderId;
        await context.setOffline(true);
        const createdOffline = await page.evaluate(() => posApp.modules.posOrder.createNewCart());
        assert.equal(createdOffline.ok,true,JSON.stringify(createdOffline));
        await page.waitForFunction(id => posApp.state.business.currentDraft.orderId !== id,onlineCart);
        const temporaryCart = (await state()).orderId;
        await scan('2099900000001'); await scan('2099900000002');
        assert.equal(await count(),2);
        await page.locator('#txtBarcode').fill('9999999999999'); await page.locator('#txtBarcode').press('Enter');
        await page.locator('#posScanGuard[open]').waitFor();
        assert.match(await page.locator('#posScanGuardMessage').innerText(), /dữ liệu offline/);
        await page.keyboard.type('2099900000001'); await page.keyboard.press('Enter');
        assert.equal(await page.locator('#posScanGuard').isVisible(), true);
        assert.equal(await count(),2);
        await page.locator('#posScanGuardConfirm').click();
        console.log('PASS blocking missing barcode popup online/offline, scanner terminators, hotkeys, explicit confirmation and focus recovery');
        await page.reload(); await page.waitForFunction(() => !!window.posApp?.state.business.currentDraft);
        await page.waitForFunction(() => document.querySelectorAll('#posScanHistoryList li').length === 2);
        await context.setOffline(false); await page.evaluate(() => PosOffline.sync());
        await page.waitForFunction(() => !PosOffline.status().pending); await page.evaluate(() => posApp.loadScreen());
        assert.equal(await count(),2,'Offline order ID remapping preserves its own history');
        assert.notEqual((await state()).orderId,temporaryCart,'Server replaces the offline cart identifier');
        await page.emulateMedia({ reducedMotion:'reduce' }); await scan('2099900000001');
        assert.equal(await page.locator('#posScanFeedback').evaluate(node => getComputedStyle(node).animationName),'none');
        assert.equal(await page.locator('#posPrimeLastScan').count(),0,'Old competing notification is removed');
        assert.deepEqual(errors,[]);
        console.log('PASS new customer isolation, offline reload and sync, reduced motion, no legacy notification or page errors');
    } catch (error) {
        await page.screenshot({ path:path.join(output,'failure.png'),fullPage:true }).catch(()=>{});
        console.error(error); console.error('BROWSER ERRORS',errors); process.exitCode = 1;
    } finally { await browser.close(); }
})();
