'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
(async () => {
    const info = JSON.parse(await new Promise(resolve => {
        let data = ''; process.stdin.on('data', chunk => data += chunk); process.stdin.on('end', () => resolve(data));
    }));
    const browser = await chromium.launch({ channel: 'chrome', headless: true });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
    const errors = []; page.on('pageerror', e => errors.push(e.message));
    const unit = id => page.locator(`#rspUnits [data-unit-id="${id}"]`);
    const pack = unit(info.packId), carton = unit(info.cartonId);
    try {
        await page.goto(info.baseUrl + '/admin/account/login');
        await page.locator('[name=UserName]').fill(info.user);
        await page.locator('[name=Password]').fill(info.password);
        if (await page.locator('[name=SelectedTerminalId]').count())
            await page.locator('[name=SelectedTerminalId]').selectOption(String(info.terminalId));
        await Promise.all([page.waitForURL(url => !url.pathname.endsWith('/login')), page.locator('button[type=submit]').click()]);
        await page.goto(info.baseUrl + '/admin/stock-documents/' + info.receiptId);
        const price = page.locator('.commercial-unit-price').first();
        await price.fill('44000');
        await page.locator('.js-receipt-selling-prices').first().click();
        await page.locator('#rspContent').waitFor({ state: 'visible' });
        assert.equal(await page.locator('#rspCost').inputValue(), '11000');
        assert.equal(await page.locator('#rspTarget').inputValue(), '10');
        assert.equal(await pack.locator('[data-field="price"]').inputValue(), '48900');
        assert.equal(await carton.locator('[data-field="price"]').inputValue(), '293400');
        await page.locator('#rspTarget').fill('20');
        assert.equal(await pack.locator('[data-field="price"]').inputValue(), '55000');
        await pack.locator('[data-field="price"]').fill('60000');
        await page.locator('#rspCost').fill('12000');
        assert.equal(await pack.locator('[data-field="price"]').inputValue(), '60000');
        await pack.locator('[data-field="wholesale"]').fill('55000');
        await page.locator('#rspWholesaleTarget').fill('8');
        assert.equal(await pack.locator('[data-field="wholesale"]').inputValue(), '55000');
        assert.match(await page.locator('#rspProductPrice').textContent(), /15[.,]000/);
        for (const checkbox of await page.locator('#rspUnits [data-field="selected"]').all()) await checkbox.uncheck();
        await pack.locator('[data-field="selected"]').check();
        await page.locator('#rspSave').click();
        await page.waitForFunction(() => document.getElementById('rspMessage').textContent.startsWith('Đã cập nhật 1'));
        assert.equal((await pack.locator('[data-out="current"]').textContent()).replace(/\D/g, ''), '60000');
        assert.equal((await carton.locator('[data-out="current"]').textContent()).replace(/\D/g, ''), '280000');
        assert.match(await pack.locator('[data-out="current-wholesale"]').textContent(), /55[.,]000/);
        await page.waitForFunction(() => document.getElementById('priceReviewCounts')?.textContent.includes('Đã cập nhật giá: 1'));
        assert.match(await page.locator('#rspHistory').textContent(), /60[.,]000/);
        assert.equal(await page.locator('#rspSave').isDisabled(), true);
        assert.equal(await page.locator('#rspPrintLabels').isVisible(), true);
        assert.match(await page.locator('#rspPrintLabels').getAttribute('href'), /label-printing\?tab=quick&variantId=\d+&units=/);
        assert.equal(await price.inputValue(), '44000', 'Price save must preserve unsaved receipt inputs');
        const output = path.resolve('TestResults/receipt-prices'); fs.mkdirSync(output, { recursive: true });
        await page.screenshot({ path: path.join(output, 'desktop.png') });
        await pack.locator('[data-field="price"]').fill('');
        assert.equal(await page.locator('#rspSave').isDisabled(), true);
        await pack.locator('[data-field="price"]').fill('61000');
        assert.equal(await page.locator('#rspSave').isDisabled(), false);
        await page.route('**/selling-prices', route => route.request().method() === 'POST' ? route.abort() : route.continue());
        await page.locator('#rspSave').click();
        await page.waitForFunction(() => document.getElementById('rspMessage').classList.contains('alert-danger'));
        assert.equal(await page.locator('#rspSave').isDisabled(), true);
        await page.unroute('**/selling-prices');
        await pack.locator('[data-field="price"]').focus();
        await page.keyboard.press('Escape');
        await page.locator('#receiptSellingPrices').waitFor({ state: 'hidden' });
        await page.locator('.js-receipt-selling-prices').first().click();
        await page.locator('#rspContent').waitFor({ state: 'visible' });
        assert.equal((await pack.locator('[data-out="current"]').textContent()).replace(/\D/g, ''), '60000');
        await page.locator('#rspReview').click();
        await page.waitForFunction(() => document.getElementById('rspMessage').textContent.startsWith('Đã ghi nhận kiểm tra'));
        await page.locator('#receiptSellingPrices').evaluate(modal => {
            if (modal.contains(document.activeElement)) document.activeElement.blur();
        });
        await page.keyboard.press('Escape');
        await page.locator('#receiptSellingPrices').waitFor({ state: 'hidden' });
        const firstRow = page.locator('.commercial-line').first();
        await page.waitForFunction(() => document.querySelector('.commercial-line')?.classList.contains('sd-price-reviewed'));
        await price.fill('45000');
        assert.ok(await firstRow.evaluate(x => x.classList.contains('sd-price-attention')));
        await price.fill('44000');
        assert.ok(await firstRow.evaluate(x => x.classList.contains('sd-price-reviewed')));
        await page.locator('#receiptPriceReviewSummary').scrollIntoViewIfNeeded();
        await page.screenshot({ path: path.join(output, 'review-summary.png') });
        await page.locator('.js-receipt-selling-prices').first().click();
        await page.locator('#rspContent').waitFor({ state: 'visible' });
        await page.setViewportSize({ width: 390, height: 844 });
        const overflow = await page.locator('#receiptSellingPrices .modal-content').evaluate(x => ({ width: x.clientWidth, scroll: x.scrollWidth }));
        assert.ok(overflow.scroll <= overflow.width + 1, JSON.stringify(overflow));
        await pack.locator('[data-field="price"]').scrollIntoViewIfNeeded();
        await page.screenshot({ path: path.join(output, 'mobile.png') });
        assert.deepEqual(errors, []);
        console.log('PASS: real UI pricing, unit factors, 10% target, manual prices preserved, selected-only immediate update, history, persistence, failure handling and mobile layout.');
    } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
