'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {chromium}=require('playwright');
(async()=>{
 const info=JSON.parse(await new Promise(resolve=>{let data='';process.stdin.on('data',x=>data+=x);process.stdin.on('end',()=>resolve(data));}));
 const browser=await chromium.launch({channel:'chrome',headless:true});
 let page;
 try {
  const context=await browser.newContext({viewport:{width:1440,height:1000}}),errors=[];page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
  await page.goto(info.baseUrl+'/admin/account/login');await page.locator('[name="UserName"]').fill(info.user);await page.locator('[name="Password"]').fill(info.password);
  await page.locator('[name="SelectedTerminalId"]').selectOption(String(info.terminalId));await page.locator('button[type="submit"]').click();
  await page.goto(info.baseUrl+`/admin/stock-documents/${info.receiptId}`);
  await page.waitForFunction(()=>document.getElementById('pricingBillConversion')?.textContent.includes('Chỉ tìm trong'));
  await page.locator('[data-workbench-tab="pricing"]').click();fs.mkdirSync(info.evidenceRoot,{recursive:true});
  assert.equal(await page.locator('#pricingAllocationLines .sd-bill-row').count(),0);
  assert.equal(await page.locator('#pricingActualBillTotal').inputValue(),'');
  const comparison=page.locator('#pricingQuantityComparison [data-product-variant-id]');
  assert.equal(await comparison.count(),1);assert.equal(await comparison.getAttribute('data-pricing-comparison-state'),'pending');
  const pendingColor=await comparison.evaluate(el=>getComputedStyle(el).backgroundColor);
  const overview=page.locator('#pricingQuantityOverview');assert.equal(await overview.getAttribute('data-state'),'pending');
  assert.equal(await overview.locator('[data-comparison-count="pending"] strong').textContent(),'1');
  const cleanTab=await context.newPage();await cleanTab.goto(info.baseUrl+`/admin/stock-documents/${info.receiptId}`);
  await cleanTab.waitForFunction(()=>document.getElementById('pricingPreview')&&!document.getElementById('pricingPreview').disabled);
  // Extra suggestions exist only in this intercepted GET, without changing fixture data.
  await page.route('**/pricing-allocation',async route=>{
   if(route.request().method()!=='GET'){await route.continue();return;}
   const response=await route.fetch(),body=await response.json(),source=body.physicalLines[0];
   body.physicalLines.push(...Array.from({length:12},(_,i)=>({...source,stockDocumentLineId:1900000000+i,productVariantId:1900000000+i,productName:`Sản phẩm phím ${i+1}`})));
   await route.fulfill({response,json:body});
  });
  await page.evaluate(()=>window.GaoAppPurchaseReceiptApproval.refreshAfterIntake());
  await page.waitForFunction(()=>document.getElementById('pricingBillConversion')?.textContent.includes('13 sản phẩm'));
  await page.locator('[data-workbench-tab="pricing"]').click();await page.mouse.move(0,0);
  const search=page.locator('#pricingBillSearch'),suggestionList=page.locator('#pricingBillSuggestions'),activeOption=suggestionList.locator('.is-active');
  await search.fill('Sản phẩm phím');await search.evaluate(el=>el.scrollIntoView({block:'center',behavior:'instant'}));assert.equal(await suggestionList.locator('button').count(),12);
  await search.press('ArrowDown');assert.equal(await activeOption.locator('strong').textContent(),'Sản phẩm phím 1');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'pricingBillSearch');assert.equal(await search.getAttribute('aria-activedescendant'),await activeOption.getAttribute('id'));
  assert.equal(await activeOption.getAttribute('aria-selected'),'true');
  assert.notEqual(await activeOption.evaluate(el=>getComputedStyle(el).backgroundColor),await suggestionList.locator('button').nth(1).evaluate(el=>getComputedStyle(el).backgroundColor));
  assert.equal(await activeOption.locator('strong').evaluate(el=>getComputedStyle(el).fontWeight),'800');
  await search.press('ArrowDown');assert.equal(await activeOption.locator('strong').textContent(),'Sản phẩm phím 2');
  await search.press('ArrowUp');await search.press('ArrowUp');assert.equal(await activeOption.locator('strong').textContent(),'Sản phẩm phím 1');
  for(let i=0;i<12;i++)await search.press('ArrowDown');
  assert.equal(await activeOption.count(),1);assert.equal(await activeOption.locator('strong').textContent(),'Sản phẩm phím 12');
  assert.ok(await suggestionList.evaluate(el=>el.scrollTop>0));
  assert.ok(await activeOption.evaluate(el=>{const row=el.getBoundingClientRect(),list=el.parentElement,bounds=list.getBoundingClientRect();return row.top>=bounds.top+list.clientTop-1&&row.bottom<=bounds.top+list.clientTop+list.clientHeight+1;}));
  await suggestionList.evaluate(el=>el.scrollIntoView({block:'center',behavior:'instant'}));
  await page.screenshot({path:path.join(info.evidenceRoot,'bill-suggestion-keyboard.png')});
  await search.press('Enter');assert.equal(await search.inputValue(),'Sản phẩm phím 12');assert.equal(await page.evaluate(()=>document.activeElement.id),'pricingBillKind');
  assert.equal(await suggestionList.isHidden(),true);assert.equal(await search.getAttribute('aria-activedescendant'),null);
  await search.fill('Sản phẩm phím');await search.press('ArrowDown');await search.fill('phím 2');
  assert.equal(await activeOption.count(),0);assert.equal(await search.getAttribute('aria-activedescendant'),null);
  await search.press('ArrowDown');await search.press('Enter');assert.equal(await search.inputValue(),'Sản phẩm phím 2');
  await search.fill('nonexistent product');await search.press('ArrowDown');await search.press('ArrowUp');await search.press('Enter');
  assert.equal(await activeOption.count(),0);assert.equal(await page.locator('#pricingAllocationLines .sd-bill-row').count(),0);
  await search.fill('Sản phẩm phím');await search.press('ArrowUp');assert.equal(await activeOption.locator('strong').textContent(),'Sản phẩm phím 12');
  await search.press('Escape');assert.equal(await suggestionList.isHidden(),true);assert.equal(await activeOption.count(),0);assert.equal(await search.getAttribute('aria-activedescendant'),null);
  await search.press('ArrowDown');assert.equal(await activeOption.locator('strong').textContent(),'Sản phẩm phím 1');
  await search.press('Tab');assert.equal(await suggestionList.isHidden(),true);assert.equal(await page.evaluate(()=>document.activeElement.id),'pricingBillKind');
  await page.unroute('**/pricing-allocation');await page.evaluate(()=>window.GaoAppPurchaseReceiptApproval.refreshAfterIntake());
  await page.waitForFunction(()=>document.getElementById('pricingBillConversion')?.textContent.includes('1 sản phẩm'));
  await page.locator('[data-workbench-tab="pricing"]').click();
  await page.locator('#pricingBillSearch').fill('nonexistent product');assert.match(await page.locator('#pricingBillSuggestions').textContent(),/Không có sản phẩm/);
  const pack=info.lines.find(x=>x.factor===4),carton=info.lines.find(x=>x.factor===24);
  await page.locator('#pricingBillSearch').fill('');
  if(info.imageUrl){
   await page.waitForFunction(src=>[...document.querySelectorAll('#pricingBillSuggestions img')].some(img=>img.getAttribute('src')===src&&img.complete&&img.naturalWidth>0),info.imageUrl);
   assert.equal(await page.locator('#pricingBillSuggestions').evaluate(el=>getComputedStyle(el).overflowY),'auto');
  }
  await page.locator('#pricingBillSuggestions button').first().click();
  const baseUnit=await page.locator('#pricingBillUnit').evaluate(el=>{const option=[...el.options].find(o=>/×1$/.test(o.textContent));return{id:option.value,name:option.textContent.replace(/ ×1$/,'')};});
  const billProductName=await page.locator('#pricingSelectedProduct strong').textContent();
  assert.equal(await page.evaluate(()=>document.activeElement.id),'pricingBillKind');
  await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'pricingBillUnit');
  await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'pricingBillQuantity');
  await page.keyboard.insertText('5');assert.equal(await page.locator('#pricingBillQuantity').inputValue(),'5');
  await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'pricingBillPriceMode');
  await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'pricingBillPrice');
  await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'pricingBillAdd');
  await page.locator('#pricingBillQuantity').click();await page.keyboard.insertText('12');assert.equal(await page.locator('#pricingBillQuantity').inputValue(),'12');
  if(info.imageUrl)assert.equal(await page.locator('#pricingSelectedProduct img').getAttribute('src'),info.imageUrl);
  await page.locator('#pricingBillUnit').selectOption(String(pack.unitId));await page.locator('#pricingBillPriceMode').selectOption('amount');
  await page.locator('#pricingBillPriceMode').focus();await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'pricingBillAmount');
  await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'pricingBillAdd');
  await page.locator('#pricingBillQuantity').fill('3');await page.locator('#pricingBillAmount').fill('100');
  assert.equal(await page.locator('#pricingBillPrice').inputValue(),'33.333333333333');assert.equal(await page.locator('#pricingBillPrice').evaluate(el=>el.readOnly),true);
  await page.locator('#pricingBillQuantity').fill('6');assert.equal(await page.locator('#pricingBillPrice').inputValue(),'16.666666666667');assert.equal(await page.locator('#pricingBillAmount').inputValue(),'100');
  await page.locator('#pricingBillQuantity').fill('0');assert.equal(await page.locator('#pricingBillPrice').inputValue(),'');await page.locator('#pricingBillAdd').click();assert.equal(await page.locator('#pricingAllocationLines .sd-bill-row').count(),0);
  await page.locator('#pricingBillQuantity').fill('3');await page.locator('#pricingBillAmount').fill('100.001');await page.locator('#pricingBillAdd').click();assert.equal(await page.locator('#pricingAllocationLines .sd-bill-row').count(),0);
  await page.locator('#pricingBillQuantity').fill('14');await page.locator('#pricingBillAmount').fill('100');assert.equal(await page.locator('#pricingBillPrice').inputValue(),'7.142857142857');await page.locator('#pricingBillAdd').click();
  let enteredPrice;await page.route('**/pricing-allocation/preview',async route=>{enteredPrice=route.request().postDataJSON().billLines[0].billUnitPriceBeforeVat;await route.continue();});
  const decimalPreview=page.waitForResponse(r=>r.url().endsWith('/pricing-allocation/preview'));await page.locator('.sd-pricing-steps [data-pricing-step="price"]').click();
  const decimalResponse=await decimalPreview;assert.equal(decimalResponse.status(),200);assert.equal((await decimalResponse.json()).systemTotal,100);assert.equal(enteredPrice,'7.142857142857');await page.unroute('**/pricing-allocation/preview');
  await page.waitForFunction(()=>!document.getElementById('pricingPreview').disabled);await page.locator('.sd-pricing-steps [data-pricing-step="bill"]').click();
  await page.locator('#pricingAllocationLines [data-bill-action="Sửa"]').first().click();assert.equal(await page.locator('#pricingBillPriceMode').inputValue(),'amount');assert.equal(await page.locator('#pricingBillAmount').inputValue(),'100');
  await page.locator('#pricingBillQuantity').fill('1');assert.equal(await page.locator('#pricingBillPrice').inputValue(),'100');await page.locator('#pricingBillAdd').click();
  await page.locator('#pricingAllocationLines [data-bill-action="Xóa"]').first().click();
  for(let i=0;i<2;i++){
   await page.locator('#pricingBillSearch').fill('');await page.locator('#pricingBillSuggestions button').first().click();await page.locator('#pricingBillPriceMode').selectOption('unit');
   await page.locator('#pricingBillPrice').fill('0.005');assert.equal(await page.locator('#pricingBillAmount').inputValue(),'0.01');await page.locator('#pricingBillAdd').click();
  }
  assert.equal(await page.locator('#pricingBillTotal').textContent(),'0,02 đ');
  for(let i=0;i<2;i++)await page.locator('#pricingAllocationLines [data-bill-action="Xóa"]').first().click();
  async function add(qty,unitId,gift=false,mode='unit'){
   await page.locator('#pricingBillSearch').fill('');await page.locator('#pricingBillSearch').click();await page.locator('#pricingBillSuggestions button').first().click();
   await page.locator('#pricingBillKind').selectOption(gift?'gift':'buy');await page.locator('#pricingBillUnit').selectOption(String(unitId));
   if(!gift)await page.locator('#pricingBillPriceMode').selectOption(mode);
   await page.locator('#pricingBillQuantity').fill(String(qty));if(!gift)await page.locator(mode==='amount'?'#pricingBillAmount':'#pricingBillPrice').fill(String(mode==='amount'?qty*100:100));
   else{assert.equal(await page.locator('#pricingBillAmount').inputValue(),'0');assert.equal(await page.locator('#pricingBillPriceMode').isDisabled(),true);}
   await page.locator('#pricingBillAdd').click();
  }
  await add(2,pack.unitId);
  const draftKey=await page.locator('#receiptPricingAllocation').evaluate(el=>`gaoapp:receipt-pricing-draft:v1:${el.dataset.draftStoreId}:${el.dataset.draftUserId}:${window.stockDocumentPage.documentId}`);
  const readRemembered=()=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)),draftKey);
  assert.equal((await readRemembered()).state.draft.billLines.length,1);assert.match(await page.locator('#pricingLocalDraftStatus').textContent(),/Đã nhớ bản nháp/);
  await cleanTab.close();assert.equal((await readRemembered()).state.draft.billLines.length,1);
  const firstBillKey=await page.locator('#pricingAllocationLines .sd-bill-row').getAttribute('data-bill-line-key');
  await page.reload();await page.waitForFunction(()=>document.getElementById('pricingAllocationMessage')?.textContent.includes('Đã khôi phục'));
  await page.locator('[data-workbench-tab="pricing"]').click();assert.equal(await page.locator('#pricingAllocationLines .sd-bill-row').count(),1);
  assert.equal(await page.locator('#pricingAllocationLines .sd-bill-row').getAttribute('data-bill-line-key'),firstBillKey);
  assert.equal(await page.locator('#pricingApply').isDisabled(),true);assert.equal(await page.evaluate(()=>window.GaoReceiptPricingAllocation.blocksConfirm()),false);
  // A partly entered row is remembered without turning it into an added bill row.
  await page.locator('#pricingBillSearch').click();await page.locator('#pricingBillSuggestions button').first().click();
  await page.locator('#pricingBillUnit').selectOption(String(carton.unitId));await page.locator('#pricingBillQuantity').fill('3');
  await page.locator('#pricingBillPriceMode').selectOption('amount');await page.locator('#pricingBillAmount').fill('300');
  await page.evaluate(()=>{window.originalPricingStorageWrite=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key.startsWith('gaoapp:receipt-pricing-draft:'))throw new DOMException('Blocked','QuotaExceededError');return window.originalPricingStorageWrite.call(this,key,value);};});
  await page.locator('#pricingBillQuantity').fill('4');assert.match(await page.locator('#pricingLocalDraftStatus').textContent(),/Chưa nhớ được/);
  await page.evaluate(()=>{Storage.prototype.setItem=window.originalPricingStorageWrite;delete window.originalPricingStorageWrite;});await page.locator('#pricingBillQuantity').fill('3');
  await page.goto(info.baseUrl+'/admin/stock-documents');await page.goto(info.baseUrl+`/admin/stock-documents/${info.receiptId}`);
  await page.waitForFunction(()=>document.getElementById('pricingAllocationMessage')?.textContent.includes('Đã khôi phục'));await page.locator('[data-workbench-tab="pricing"]').click();
  assert.equal(await page.locator('#pricingAllocationLines .sd-bill-row').count(),1);assert.equal(await page.locator('#pricingBillQuantity').inputValue(),'3');
  assert.equal(await page.locator('#pricingBillUnit').inputValue(),String(carton.unitId));assert.equal(await page.locator('#pricingBillPriceMode').inputValue(),'amount');
  assert.equal(await page.locator('#pricingBillAmount').inputValue(),'300');assert.equal(await page.locator('#pricingBillPrice').inputValue(),'100');
  assert.equal(await page.locator('#pricingSave').isDisabled(),true);await page.locator('#receiptPricingAllocation').screenshot({path:path.join(info.evidenceRoot,'local-draft-partial-bill-restored.png')});
  const reopened=await page.context().newPage();await reopened.goto(info.baseUrl+`/admin/stock-documents/${info.receiptId}`);
  await reopened.waitForFunction(()=>document.getElementById('pricingAllocationMessage')?.textContent.includes('Đã khôi phục'));assert.equal(await reopened.locator('#pricingBillAmount').inputValue(),'300');await reopened.close();
  await page.locator('#pricingBillCancelEdit').click();assert.equal(await page.locator('#pricingBillSearch').inputValue(),'');
  // A different user/store/receipt scope cannot consume this receipt's local input.
  const scopeRecord=await readRemembered();await page.evaluate(({key,record})=>localStorage.setItem(key,JSON.stringify({...record,scope:key+':other-user'})),{key:draftKey,record:scopeRecord});
  const isolated=await page.context().newPage();await isolated.goto(info.baseUrl+`/admin/stock-documents/${info.receiptId}`);
  await isolated.waitForFunction(()=>document.getElementById('pricingPreview')&&!document.getElementById('pricingPreview').disabled);
  assert.equal(await isolated.locator('#pricingAllocationLines .sd-bill-row').count(),0);await isolated.close();
  await page.evaluate(({key,record})=>localStorage.setItem(key,JSON.stringify(record)),{key:draftKey,record:scopeRecord});await page.reload();
  await page.waitForFunction(()=>document.getElementById('pricingAllocationMessage')?.textContent.includes('Đã khôi phục'));await page.locator('[data-workbench-tab="pricing"]').click();
  await page.locator('#pricingAllocationLines [data-bill-action="Xóa"]').click();await page.reload();
  await page.waitForFunction(()=>document.getElementById('pricingAllocationMessage')?.textContent.includes('Đã khôi phục'));assert.equal(await page.locator('#pricingAllocationLines .sd-bill-row').count(),0);
  await page.locator('[data-workbench-tab="pricing"]').click();await add(2,pack.unitId);await add(48,baseUnit.id);
  assert.equal(await overview.getAttribute('data-state'),'matched');assert.equal(await overview.locator('[data-comparison-count="matched"] strong').textContent(),'1');
  await overview.screenshot({path:path.join(info.evidenceRoot,'quantity-overview-matched.png')});
  assert.equal(await comparison.count(),1);assert.equal(await comparison.getAttribute('data-pricing-comparison-state'),'matched');
  assert.match(await comparison.locator('[data-comparison="received-detail"]').textContent(),/2 Lốc.*×4.*2 Thùng.*×24/);
  assert.ok((await comparison.locator('[data-comparison="bill-detail"]').textContent()).includes(`48 ${baseUnit.name}`));
  const matchedColor=await comparison.evaluate(el=>getComputedStyle(el).backgroundColor);assert.notEqual(matchedColor,pendingColor);
  await page.locator('#pricingBillSearch').press('Escape');await comparison.screenshot({path:path.join(info.evidenceRoot,'comparison-mixed-units-matched.png')});
  await add(1,baseUnit.id);assert.equal(await comparison.getAttribute('data-pricing-comparison-state'),'mismatch');
  assert.equal(await overview.getAttribute('data-state'),'mismatch');assert.equal(await overview.locator('[data-comparison-count="mismatch"] strong').textContent(),'1');
  await overview.screenshot({path:path.join(info.evidenceRoot,'quantity-overview-mismatch.png')});
  assert.ok((await comparison.textContent()).includes(`Thực nhận thiếu 1 ${baseUnit.name} so với bill`));
  const mismatchColor=await comparison.evaluate(el=>getComputedStyle(el).backgroundColor);assert.notEqual(mismatchColor,matchedColor);assert.notEqual(mismatchColor,pendingColor);
  await page.locator('#pricingBillSearch').press('Escape');await comparison.screenshot({path:path.join(info.evidenceRoot,'comparison-mixed-units-mismatch.png')});
  for(let i=0;i<3;i++)await page.locator('#pricingAllocationLines [data-bill-action="Xóa"]').first().click();
  assert.equal(await comparison.getAttribute('data-pricing-comparison-state'),'pending');
  await add(.000125,pack.unitId);await add(.000125,pack.unitId);
  assert.ok((await comparison.textContent()).includes(`0,002 ${baseUnit.name}`));
  const roundedQuantities=page.waitForResponse(r=>r.url().endsWith('/pricing-allocation/preview'));await page.locator('.sd-pricing-steps [data-pricing-step="price"]').click();
  assert.equal((await(await roundedQuantities).json()).quantities[0].purchasedBaseQuantity,.002);
  await page.waitForFunction(()=>!document.getElementById('pricingPreview').disabled);await page.locator('.sd-pricing-steps [data-pricing-step="bill"]').click();
  for(let i=0;i<2;i++)await page.locator('#pricingAllocationLines [data-bill-action="Xóa"]').first().click();
  await add(1,pack.unitId);await add(.75,pack.unitId,false,'amount');await add(2,carton.unitId,false,'amount');await add(.25,pack.unitId,true);
  assert.equal(await page.locator('#pricingAllocationLines .sd-bill-row').count(),4);
  if(info.imageUrl)assert.equal(await page.locator('#pricingAllocationLines img').count(),4);
  await page.locator('#pricingBillSearch').fill('');await page.locator('#pricingBillSuggestions button').first().click();await page.locator('#pricingBillPriceMode').selectOption('unit');await page.locator('#pricingBillPrice').fill('100');await page.locator('#pricingBillQuantity').fill('2');
  assert.equal(await page.locator('#pricingBillAmount').inputValue(),'200');assert.equal(await page.locator('#pricingBillAmount').evaluate(el=>el.readOnly),true);await page.locator('#pricingBillPrice').fill('');await page.locator('#pricingBillSearch').fill('');
  assert.match(await page.locator('#pricingQuantitySummary').textContent(),/1\/1 khớp/);
  await page.locator('#pricingBillSearch').press('Escape');await page.screenshot({path:path.join(info.evidenceRoot,'bill-lines-desktop.png'),fullPage:true});
  const keys=await page.locator('#pricingAllocationLines .sd-bill-row').evaluateAll(rows=>rows.map(r=>r.dataset.billLineKey));
  await page.locator('.sd-pricing-steps [data-pricing-step="program"]').click();await page.locator('#pricingNewProgram').click();
  const programSearch=page.locator('#pricingRuleSearch'),programSuggestions=page.locator('#pricingRuleSuggestions');
  async function chooseProgramBill(key,query=''){
   await programSearch.fill(query);await programSearch.click();await programSuggestions.locator(`[data-program-bill-key="${key}"]`).click();
  }
  assert.equal(await page.locator('#pricingRuleSources input[type="checkbox"]').count(),0);
  await programSearch.click();assert.deepEqual(await programSuggestions.locator('[data-program-bill-key]').evaluateAll(rows=>rows.map(r=>r.dataset.programBillKey)),keys);
  assert.match(await programSuggestions.locator('button').first().textContent(),/Dòng 1.*Hàng mua.*1 Lốc.*100 đ.*Thành tiền 100 đ/);
  assert.match(await programSuggestions.locator('button').last().textContent(),/Dòng 4.*Quà tặng.*0,25 Lốc.*0 đ/);
  await programSearch.press('ArrowDown');await programSearch.press('Enter');assert.equal(await page.locator(`[data-source-quantity="${keys[0]}"]`).inputValue(),'1');
  await page.locator(`[data-source-quantity="${keys[0]}"]`).fill('0.5');await page.locator(`[data-source-quantity="${keys[0]}"]`).press('Enter');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'pricingRuleSearch');assert.equal(await programSuggestions.isVisible(),true);
  assert.deepEqual(await programSuggestions.locator('[data-program-bill-key]').evaluateAll(rows=>rows.map(r=>r.dataset.programBillKey)),keys.slice(1));
  await programSearch.press('ArrowDown');await programSearch.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.dataset.sourceQuantity),keys[1]);
  assert.equal(await page.locator(`[data-source-quantity="${keys[1]}"]`).inputValue(),'0.75');await page.locator(`[data-source-quantity="${keys[1]}"]`).press('Enter');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'pricingRuleSearch');assert.equal(await page.locator('#pricingRuleList .sd-pricing-rule').count(),0);
  assert.equal((await readRemembered()).state.editor.value.sources[keys[0]],.5);assert.equal((await readRemembered()).state.editor.value.sources[keys[1]],.75);
  await page.locator(`[data-selected-source-bill-key="${keys[1]}"] button`).click();
  await page.locator(`[data-selected-source-bill-key="${keys[0]}"] button`).click();assert.equal(await page.locator('[data-source-quantity]').count(),0);
  await programSearch.fill('Dòng 4');await programSearch.press('ArrowDown');await programSearch.press('Enter');assert.equal(await page.locator('[data-gift-quantity="0"]').inputValue(),'0.25');
  await page.locator('[data-gift-quantity="0"]').fill('0.125');await page.locator('[data-gift-bill-key] button').click();assert.equal(await page.locator('[data-gift-quantity]').count(),0);
  await page.locator('#pricingExtraGiftChooser summary').click();await page.locator('#pricingExtraGiftSearch').fill(billProductName);await page.locator('#pricingExtraGiftSuggestions button').first().click();
  assert.equal(await page.locator('[data-gift-quantity="0"]').inputValue(),'1');await page.locator('#pricingGiftTargets .sd-pricing-gift-row button').click();
  await page.locator('#pricingCloseRule').click();await page.locator('#pricingNewProgram').click();
  await page.locator('#pricingRuleType').selectOption(info.fixedDiscountAmount?'3':'2');await chooseProgramBill(keys[2]);
  if(info.fixedDiscountAmount)await page.locator('#pricingRuleDiscountAmount').fill(String(info.fixedDiscountAmount));
  assert.equal(await page.locator(`[data-source-quantity="${keys[2]}"]`).inputValue(),'2');await page.locator('#pricingSaveRule').click();
  assert.equal(await page.locator('#pricingRuleList .sd-pricing-rule strong').first().textContent(),info.fixedDiscountAmount?'Giảm 20 đ':'Giảm 10%');
  // Remaining availability is per bill row, across programs, and sources shared by
  // several gift rules in one program must be reserved only once.
  async function remainingChoices(){
   await programSearch.fill('');await programSearch.click();
   return programSuggestions.locator('[data-program-bill-key]').evaluateAll(rows=>rows.map(r=>({key:r.dataset.programBillKey,quantity:Number(r.dataset.programAvailableQuantity)})));
  }
  await page.locator('#pricingNewProgram').click();
  assert.deepEqual(await remainingChoices(),[{key:keys[0],quantity:1},{key:keys[1],quantity:.75},{key:keys[3],quantity:.25}]);
  await programSearch.fill('Dòng 3');assert.equal(await programSuggestions.locator('[data-program-bill-key]').count(),0);
  await chooseProgramBill(keys[0]);await page.locator(`[data-source-quantity="${keys[0]}"]`).fill('0.3');
  await chooseProgramBill(keys[3]);await page.locator('[data-gift-quantity="0"]').fill('0.1');
  await page.locator('#pricingExtraGiftChooser summary').click();await page.locator('#pricingExtraGiftSearch').fill(billProductName);await page.locator('#pricingExtraGiftSuggestions button').first().click();
  await page.locator('[data-gift-quantity="1"]').fill('0.1');await page.locator('.sd-program-optional-name summary').click();await page.locator('#pricingRuleName').fill('Kiểm tra phần còn lại');
  await page.locator('#pricingSaveRule').click();assert.equal(await page.locator('#pricingRuleList .sd-pricing-rule').count(),2);
  const partialCard=page.locator('#pricingRuleList .sd-pricing-rule').filter({has:page.locator('strong',{hasText:'Kiểm tra phần còn lại'})});
  await page.locator('#pricingNewProgram').click();
  assert.deepEqual(await remainingChoices(),[{key:keys[0],quantity:.7},{key:keys[1],quantity:.75},{key:keys[3],quantity:.15}]);
  assert.match(await programSuggestions.locator(`[data-program-bill-key="${keys[0]}"]`).textContent(),/Còn lại: 0,7 Lốc.*70 đ/);
  await page.locator('#pricingRuleEditor').screenshot({path:path.join(info.evidenceRoot,'program-remaining-quantities.png')});
  await chooseProgramBill(keys[3]);assert.equal(await page.locator('[data-gift-quantity="0"]').inputValue(),'0.15');assert.equal(await page.locator('[data-gift-quantity="0"]').getAttribute('max'),'0.15');
  await chooseProgramBill(keys[1]);await page.locator('[data-gift-quantity="0"]').fill('0.2');await page.locator('#pricingSaveRule').click();assert.match(await page.locator('#pricingRuleError').textContent(),/chỉ còn 0,15/);
  await page.locator('#pricingCloseRule').click();await page.locator('#pricingNewProgram').click();await page.locator('#pricingRuleType').selectOption('2');
  assert.deepEqual(await remainingChoices(),[{key:keys[0],quantity:.7},{key:keys[1],quantity:.75}]);
  await chooseProgramBill(keys[0]);assert.equal(await page.locator(`[data-source-quantity="${keys[0]}"]`).inputValue(),'0.7');assert.equal(await page.locator(`[data-source-quantity="${keys[0]}"]`).getAttribute('max'),'0.7');
  await page.locator(`[data-source-quantity="${keys[0]}"]`).fill('0.8');await page.locator('#pricingSaveRule').click();assert.match(await page.locator('#pricingRuleError').textContent(),/chỉ còn 0,7/);
  await page.locator('#pricingCloseRule').click();
  await partialCard.locator('button',{hasText:'Sửa'}).click();assert.equal(await page.locator(`[data-source-quantity="${keys[0]}"]`).inputValue(),'0.3');assert.equal(await page.locator(`[data-source-quantity="${keys[0]}"]`).getAttribute('max'),'1');
  assert.equal(await page.locator('[data-gift-quantity="0"]').getAttribute('max'),'0.25');await page.locator(`[data-selected-source-bill-key="${keys[0]}"] button`).click();
  await chooseProgramBill(keys[0]);assert.equal(await page.locator(`[data-source-quantity="${keys[0]}"]`).inputValue(),'1');await page.locator('#pricingCloseRule').click();
  await page.locator('#pricingNewProgram').click();await chooseProgramBill(keys[0]);assert.equal(await page.locator(`[data-source-quantity="${keys[0]}"]`).inputValue(),'0.7');
  await partialCard.locator('button',{hasText:'Gỡ'}).click();assert.equal(await page.locator(`[data-source-quantity="${keys[0]}"]`).getAttribute('max'),'1');
  assert.deepEqual(await remainingChoices(),[{key:keys[1],quantity:.75},{key:keys[3],quantity:.25}]);await page.locator('#pricingCloseRule').click();
  const discountCard=page.locator('#pricingRuleList .sd-pricing-rule').first();await discountCard.locator('button',{hasText:'Sửa'}).click();
  assert.equal(await page.locator(`[data-source-quantity="${keys[2]}"]`).getAttribute('max'),'2');await page.locator('#pricingCloseRule').click();
  await page.locator('#pricingNewProgram').click();await chooseProgramBill(keys[1]);await chooseProgramBill(keys[0]);
  assert.deepEqual(await page.locator('[data-selected-source-bill-key]').evaluateAll(rows=>rows.map(r=>r.dataset.selectedSourceBillKey)),keys.slice(0,2));
  assert.equal(await page.locator(`[data-source-quantity="${keys[0]}"]`).inputValue(),'1');await page.locator(`[data-source-quantity="${keys[0]}"]`).fill('0.5');
  await chooseProgramBill(keys[3]);
  assert.equal(await page.locator('[data-gift-quantity="0"]').inputValue(),'0.25');await page.locator('.sd-program-optional-name summary').click();await page.locator('#pricingRuleName').fill('Mua một phần dòng 1 + dòng 2, tặng dòng 4');
  await page.locator('#pricingRuleEditor').screenshot({path:path.join(info.evidenceRoot,'program-typed-selection.png')});
  await page.reload();await page.waitForFunction(()=>document.getElementById('pricingRuleEditor')?.hidden===false);await page.locator('[data-workbench-tab="pricing"]').click();
  assert.equal(await page.locator('#pricingRuleList .sd-pricing-rule').count(),1);assert.equal(await page.locator(`[data-source-quantity="${keys[0]}"]`).inputValue(),'0.5');
  assert.equal(await page.locator('[data-gift-quantity="0"]').inputValue(),'0.25');assert.equal(await page.locator('#pricingRuleName').inputValue(),'Mua một phần dòng 1 + dòng 2, tặng dòng 4');
  await page.locator('#pricingRuleEditor').screenshot({path:path.join(info.evidenceRoot,'local-draft-program-restored.png')});
  await page.evaluate(()=>window.GaoAppPurchaseReceiptApproval.refreshAfterIntake());
  await page.waitForFunction(()=>document.getElementById('pricingRuleEditor')?.hidden===false);
  await page.locator('[data-workbench-tab="pricing"]').click();
  assert.equal(await page.locator('#pricingAllocationLines .sd-bill-row').count(),4);
  assert.equal(await page.locator(`[data-source-quantity="${keys[0]}"]`).inputValue(),'0.5');
  assert.equal(await page.locator('#pricingRuleName').inputValue(),'Mua một phần dòng 1 + dòng 2, tặng dòng 4');
  assert.equal(await page.evaluate(()=>window.GaoReceiptPricingAllocation.blocksConfirm()),false);
  await page.screenshot({path:path.join(info.evidenceRoot,'program-partial-quantity.png'),fullPage:true});await page.locator('#pricingSaveRule').click();
  assert.equal(await page.locator('#pricingRuleList .sd-pricing-rule').count(),2);
  assert.match(await page.locator('#pricingProgramQuantityComparison').textContent(),/Khớp số lượng/);
  await page.locator('#pricingNewProgram').click();await page.locator('#pricingRuleType').selectOption('3');await chooseProgramBill(keys[0]);
  assert.equal(await page.locator(`[data-source-quantity="${keys[0]}"]`).inputValue(),'0.5');assert.equal(await page.locator(`[data-source-quantity="${keys[0]}"]`).getAttribute('max'),'0.5');
  await page.locator(`[data-source-quantity="${keys[0]}"]`).fill('2');await page.locator('#pricingRuleDiscountAmount').fill('5');await page.locator('#pricingSaveRule').click();
  assert.match(await page.locator('#pricingRuleError').textContent(),/không vượt số lượng/);
  await page.locator(`[data-source-quantity="${keys[0]}"]`).fill('0.75');await page.locator('#pricingSaveRule').click();assert.match(await page.locator('#pricingRuleError').textContent(),/chỉ còn 0,5/);
  await page.locator(`[data-source-quantity="${keys[0]}"]`).fill('0.5');await page.locator('#pricingRuleDiscountAmount').fill('0.001');await page.locator('#pricingSaveRule').click();
  assert.match(await page.locator('#pricingRuleError').textContent(),/hai số lẻ/);await page.locator('#pricingRuleDiscountAmount').fill('5');
  await page.locator('#pricingRuleDiscountAmount').fill('50');await page.locator('#pricingSaveRule').click();assert.match(await page.locator('#pricingRuleError').textContent(),/nhỏ hơn tổng tiền hàng/);
  await page.locator('#pricingRuleDiscountAmount').fill('5');assert.equal(await page.locator('#pricingRuleError').textContent(),'');
  await page.locator('#pricingRuleEditor').screenshot({path:path.join(info.evidenceRoot,'program-fixed-amount.png')});
  await page.setViewportSize({width:390,height:844});await page.locator('#pricingRuleEditor').screenshot({path:path.join(info.evidenceRoot,'program-fixed-amount-mobile.png')});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));await page.setViewportSize({width:1440,height:1000});
  await page.evaluate(()=>window.GaoAppPurchaseReceiptApproval.refreshAfterIntake());await page.waitForFunction(()=>document.getElementById('pricingRuleEditor')?.hidden===false);
  await page.locator('[data-workbench-tab="pricing"]').click();assert.equal(await page.locator('#pricingRuleType').inputValue(),'3');assert.equal(await page.locator('#pricingRuleDiscountAmount').inputValue(),'5');
  assert.equal(await page.locator(`[data-source-quantity="${keys[0]}"]`).inputValue(),'0.5');await page.locator('#pricingSaveRule').click();
  const fixedPreview=page.waitForResponse(r=>r.url().endsWith('/pricing-allocation/preview'));await page.locator('.sd-pricing-steps [data-pricing-step="price"]').click();
  const fixedResult=await(await fixedPreview).json();assert.equal(fixedResult.systemTotal,350);assert.ok(fixedResult.rules.some(r=>r.amount===5));
  await page.waitForFunction(()=>!document.getElementById('pricingPreview').disabled);await page.locator('.sd-pricing-steps [data-pricing-step="program"]').click();
  await page.locator('#pricingNewProgram').click();assert.deepEqual(await remainingChoices(),[]);assert.match(await programSuggestions.textContent(),/đã dùng hết/);await page.locator('#pricingCloseRule').click();
  const fixedCard=page.locator('#pricingRuleList .sd-pricing-rule').filter({has:page.locator('strong',{hasText:'Giảm 5 đ'})});
  await fixedCard.locator('button',{hasText:'Sửa'}).click();assert.equal(await page.locator('#pricingRuleDiscountAmount').inputValue(),'5');assert.equal(await page.locator('#pricingRuleName').inputValue(),'');
  await page.locator('#pricingCloseRule').click();await fixedCard.locator('button',{hasText:'Gỡ'}).click();
  await page.route('**/pricing-allocation',async route=>{if(route.request().method()!=='GET'){await route.continue();return;}const response=await route.fetch();const body=await response.json();body.physicalLines=[];await route.fulfill({response,json:body});});
  await page.evaluate(()=>window.GaoAppPurchaseReceiptApproval.refreshAfterIntake());
  await page.waitForFunction(()=>document.getElementById('pricingProgramQuantityComparison')?.textContent.includes('không còn trong thực nhận'));
  assert.equal(await page.locator('#pricingAllocationLines .sd-bill-row').count(),4);assert.equal(await page.locator('#pricingRuleList .sd-pricing-rule').count(),2);
  assert.equal(await page.locator('#pricingApply').isDisabled(),true);
  await page.unroute('**/pricing-allocation');await page.evaluate(()=>window.GaoAppPurchaseReceiptApproval.refreshAfterIntake());
  await page.waitForFunction(()=>document.getElementById('pricingQuantitySummary')?.textContent==='1/1 khớp');
  await page.locator('[data-workbench-tab="pricing"]').click();
  assert.deepEqual(await page.locator('#pricingAllocationLines .sd-bill-row').evaluateAll(rows=>rows.map(r=>r.dataset.billLineKey)),keys);
  await page.locator('.sd-pricing-steps [data-pricing-step="price"]').click();
  await page.waitForFunction(()=>!document.getElementById('pricingPreview').disabled);
  await page.locator('#pricingActualBillTotal').fill('354');
  const pending=page.waitForResponse(r=>r.url().endsWith('/pricing-allocation/preview'));await page.locator('#pricingPreview').click();const result=await(await pending).json();
  assert.equal(result.canApply,false);assert.equal(result.systemTotal,355);assert.equal(result.difference,1);assert.equal(result.quantities[0].giftBaseQuantity,1);
  assert.equal(await page.locator('#pricingApply').isDisabled(),true);
  const priceRows=page.locator('#pricingFinalPrices [data-pricing-line-id]');
  assert.match(await priceRows.nth(0).locator('[data-pricing-result="unitPrice"]').textContent(),/^25,36 đ\//);
  assert.match(await priceRows.nth(1).locator('[data-pricing-result="unitPrice"]').textContent(),/^152,15 đ\//);
  await page.screenshot({path:path.join(info.evidenceRoot,'pricing-preview-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(info.evidenceRoot,'pricing-preview-mobile.png'),fullPage:true});await page.setViewportSize({width:1440,height:1000});
  await page.locator('#pricingActualBillTotal').fill('355');assert.equal(await priceRows.nth(0).locator('[data-pricing-result="unitPrice"]').textContent(),'—');
  await page.route('**/pricing-allocation/preview',async route=>{const response=await route.fetch();await page.locator('#pricingGlobalDiscount').fill('1');await route.fulfill({response});});
  const late=page.waitForResponse(r=>r.url().endsWith('/pricing-allocation/preview'));await page.locator('#pricingPreview').click();await late;await page.waitForFunction(()=>!document.getElementById('pricingPreview').disabled);
  assert.equal(await priceRows.nth(0).locator('[data-pricing-result="unitPrice"]').textContent(),'—');await page.unroute('**/pricing-allocation/preview');await page.locator('#pricingGlobalDiscount').fill('0');
  const beforeSaveRecord=await readRemembered();
  const save=page.waitForResponse(r=>r.url().endsWith('/pricing-allocation')&&r.request().method()==='PUT');await page.locator('#pricingSave').click();const saved=await save;
  assert.equal(saved.status(),200,await saved.text());const graph=await saved.json();assert.equal(graph.draft.billLines.length,4);
  assert.deepEqual(graph.draft.billLines.map(x=>x.billLineKey),keys);assert.ok(graph.draft.rules.some(r=>r.billSources.some(s=>s.billLineKey===keys[0]&&s.quantity===.5)));
  if(info.fixedDiscountAmount){assert.ok(graph.draft.rules.some(r=>r.discountAmount===info.fixedDiscountAmount&&r.discountPercent===0));}
  await page.waitForFunction(key=>localStorage.getItem(key)===null,draftKey);
  await page.locator('.sd-pricing-steps [data-pricing-step="program"]').click();await page.locator('#pricingNewProgram').click();
  assert.deepEqual(await remainingChoices(),[{key:keys[0],quantity:.5}]);await page.locator('#pricingCloseRule').click();await page.locator('.sd-pricing-steps [data-pricing-step="price"]').click();
  await page.waitForFunction(()=>!document.getElementById('pricingApply').disabled);
  const apply=page.waitForResponse(r=>r.url().endsWith('/pricing-allocation/apply'));await page.locator('#pricingApply').click();assert.equal((await apply).status(),200);
  await page.waitForFunction(()=>document.getElementById('commercialApprovalWorkbench').dataset.allocationApplied==='true');assert.equal(await page.locator('.commercial-unit-price[readonly]').count(),0);
  assert.match(await page.locator('#pricingAllocationMessage').textContent(),/Đã điền giá nhập/);assert.equal(await page.locator('#commercialApproveButton').count(),1);
  await page.locator('[data-workbench-tab="goods"]').click();
  const goodsPrice=page.locator(`.commercial-line[data-line-id="${info.lines.find(x=>x.factor===4).id}"] .commercial-unit-price`);
  const originalGoodsPrice=await goodsPrice.inputValue();
  const otherGoodsAmount=await page.locator(`.commercial-line[data-line-id="${info.lines.find(x=>x.factor===24).id}"]`).getAttribute('data-exact-before-vat');
  const expectedManualSubtotal=new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2}).format(240+Number(otherGoodsAmount))+' đ';
  const manualSave=page.waitForResponse(r=>r.url().endsWith('/price-draft')&&r.request().method()==='POST');
  await goodsPrice.fill('120');assert.equal(await page.locator('#commercialSubtotal').textContent(),expectedManualSubtotal);
  const manualResponse=await manualSave;assert.equal(manualResponse.status(),200,await manualResponse.text());
  await page.waitForFunction(()=>!window.GaoReceiptPriceDrafts.hasUnsaved());
  assert.equal(await page.locator('#receiptPriceDraftSave').isVisible(),true);
  assert.equal(await page.evaluate(()=>window.GaoReceiptPricingAllocation.blocksConfirm()),false);
  await page.screenshot({path:path.join(info.evidenceRoot,'goods-manual-price-after-apply.png'),fullPage:true});
  await page.reload();await page.locator('[data-workbench-tab="goods"]').click();
  await page.waitForFunction(()=>!document.getElementById('pricingReload').disabled);
  assert.equal(await goodsPrice.inputValue(),'120');assert.equal(await page.locator('#commercialSubtotal').textContent(),expectedManualSubtotal);
  // Reloading and saving the helper retain manual Goods prices. Only Apply overwrites them.
  await page.locator('[data-workbench-tab="pricing"]').click();await page.locator('#pricingReload').click();
  await page.waitForFunction(()=>!document.getElementById('pricingReload').disabled);
  assert.equal(await goodsPrice.inputValue(),'120');
  await page.locator('.sd-pricing-steps [data-pricing-step="price"]').click();
  await page.waitForFunction(()=>!document.getElementById('pricingSave').disabled);
  const helperSave=page.waitForResponse(r=>r.url().endsWith('/pricing-allocation')&&r.request().method()==='PUT');await page.locator('#pricingSave').click();assert.equal((await helperSave).status(),200);
  await page.waitForFunction(()=>!document.getElementById('pricingApply').disabled);assert.equal(await goodsPrice.inputValue(),'120');
  const reapply=page.waitForResponse(r=>r.url().endsWith('/pricing-allocation/apply'));await page.locator('#pricingApply').click();assert.equal((await reapply).status(),200);
  await page.waitForFunction(()=>!document.getElementById('pricingReload').disabled);assert.equal(await goodsPrice.inputValue(),originalGoodsPrice);
  assert.equal(await page.evaluate(()=>window.GaoReceiptPriceDrafts.hasUnsaved()),false);
  await page.screenshot({path:path.join(info.evidenceRoot,'pricing-applied-desktop.png'),fullPage:true});
  // An old browser draft must not silently replace a newer saved/applied plan.
  await page.evaluate(({key,record})=>localStorage.setItem(key,JSON.stringify(record)),{key:draftKey,record:beforeSaveRecord});
  const newerPlan=await page.context().newPage();await newerPlan.goto(info.baseUrl+`/admin/stock-documents/${info.receiptId}`);
  await newerPlan.waitForFunction(()=>document.getElementById('pricingRestoreLocalDraft')?.hidden===false);
  assert.match(await newerPlan.locator('#pricingLocalDraftStatus').textContent(),/máy chủ đã thay đổi/);assert.equal(await newerPlan.locator('.commercial-unit-price[readonly]').count(),0);
  assert.equal(await newerPlan.evaluate(()=>window.GaoReceiptPricingAllocation.blocksConfirm()),false);
  await newerPlan.locator('[data-workbench-tab="pricing"]').click();newerPlan.once('dialog',dialog=>dialog.accept());await newerPlan.locator('#pricingReload').click();
  await newerPlan.waitForFunction(key=>localStorage.getItem(key)===null,draftKey);assert.equal(await newerPlan.locator('#pricingRestoreLocalDraft').isHidden(),true);await newerPlan.close();
  await page.setViewportSize({width:390,height:844});await page.locator('.sd-pricing-steps [data-pricing-step="bill"]').click();await page.screenshot({path:path.join(info.evidenceRoot,'bill-lines-mobile.png'),fullPage:true});
  assert.deepEqual(errors,[]);console.log('PASS: manual Goods prices remain editable after Apply, autosave and survive reload/helper save; re-Apply explicitly replaces them; bill/program drafts, remaining program quantities, exact totals and Apply without posting; desktop/mobile.');
 }catch(error){
  await page.screenshot({path:path.join(info.evidenceRoot,'pricing-failure.png'),fullPage:true});
  console.error(await page.evaluate(()=>({message:document.getElementById('pricingAllocationMessage')?.textContent,
   priceState:document.getElementById('receiptPriceDraftStatus')?.textContent,
   unsaved:window.GaoReceiptPriceDrafts?.hasUnsaved(), saveDisabled:document.getElementById('pricingSave')?.disabled,
   errors:[...document.querySelectorAll('.commercial-price-save-state')].map(x=>x.textContent)})));
  throw error;
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
