const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
(async () => {
    const info = JSON.parse(await new Promise(resolve => { let value = ''; process.stdin.on('data', data => value += data); process.stdin.on('end', () => resolve(value)); }));
    const output = path.resolve('TestResults/role-permissions/browser'); fs.mkdirSync(output, { recursive: true });
    const browser = await chromium.launch({ channel: 'chrome', headless: true });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    const checkbox = code => page.locator('.rp-permission').filter({ has: page.locator('code', { hasText: new RegExp('^' + code.replaceAll('.', '\\.') + '$') }) }).locator('.permission-checkbox');
    const search = value => page.locator('#permissionSearch').fill(value);
    const clear = () => page.locator('#clearFilters').click();
    async function save() {
        await page.locator('#reviewChanges').click();
        assert.equal(await page.locator('#changesDialog').evaluate(node => node.open), true);
        await Promise.all([page.waitForNavigation(), page.locator('#confirmSave').click()]);
        assert.equal(await page.locator('#changedPermissionCount').innerText(), '0');
    }
    try {
        await page.goto(info.baseUrl + '/admin/account/login');
        await page.locator('[name=UserName]').fill(info.user); await page.locator('[name=Password]').fill(info.password);
        if (await page.locator('[name=SelectedTerminalId]').count()) await page.locator('[name=SelectedTerminalId]').selectOption(String(info.terminalId));
        await Promise.all([page.waitForURL(url => !url.pathname.endsWith('/login')), page.locator('#loginForm button[type=submit]').click()]);
        await page.goto(info.baseUrl + '/Admin/RolePermissions');
        assert.equal(await page.locator('.rp-empty-start').isVisible(), true);
        await page.locator('a[href*="Roles/Create" i]').first().click();
        await page.locator('[name=Code]').fill('thu_ngan_browser');
        await page.locator('[name=Name]').fill('Thu ngân & in tem');
        await Promise.all([page.waitForURL(url => url.pathname.toLowerCase().includes('rolepermissions')), page.getByRole('button', { name: 'Tạo vai trò & chọn quyền', exact: true }).click()]);
        assert.ok(await page.locator('.permission-checkbox').count() >= 200);
        assert.equal(await page.locator('#selectedPermissionCount').innerText(), '0');
        assert.equal(await page.locator('#reviewChanges').isDisabled(), true);
        const texts = await page.locator('.rp-permission-text > span').allInnerTexts();
        assert.ok(texts.every(text => !/\b(permission|role|user|store|refund|terminal|integration|valuation|issue|background|audit)\b/i.test(text)), JSON.stringify(texts));
        assert.equal(await page.locator('.rp-permission-code:visible').count(), 0);
        await page.locator('#showCodes').check();
        assert.ok(await page.locator('.rp-permission-code:visible').count() >= 200);
        await page.locator('#showCodes').uncheck();
        for (const width of [1440, 1024, 768, 390, 360]) {
            await page.setViewportSize({ width, height: 950 });
            assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'Horizontal overflow at ' + width);
            await page.screenshot({ path: path.join(output, 'permissions-' + width + '.png') });
        }
        await page.setViewportSize({ width: 1440, height: 1000 });
        await search('in tem');
        assert.equal(await page.locator('.rp-permission:visible').count(), 2);
        await page.locator('#selectVisible').click();
        assert.equal(await page.locator('#selectedPermissionCount').innerText(), '2');
        await clear(); await search('pos.order.view'); await checkbox('pos.order.view').check();
        assert.equal(await page.locator('#selectedPermissionCount').innerText(), '3');
        await page.locator('#reviewChanges').click();
        assert.equal(await page.locator('#changesList li').count(), 3);
        await page.keyboard.press('Escape');
        assert.equal(await page.locator('#changesDialog').evaluate(node => node.open), false);
        assert.equal(await page.locator('#changedPermissionCount').innerText(), '3');
        await save();
        assert.equal(await page.locator('#selectedPermissionCount').innerText(), '3');
        assert.equal(await checkbox('system.productlabel.print').isChecked(), true);
        assert.equal(await checkbox('system.productlabel.manage').isChecked(), true);
        assert.equal(await checkbox('pos.order.view').isChecked(), true);
        console.log('PASS create role, Vietnamese labels, accentless search, filtered bulk selection and real save preserving hidden grants.');
        await search('hoan tien');
        await page.locator('.rp-group-tab').filter({ hasText: 'Bán hàng & thu ngân' }).click();
        assert.equal(await page.locator('.rp-permission:visible').count(), 2);
        await page.locator('#selectVisible').click();
        await clear(); await search('in tem'); await checkbox('system.productlabel.manage').uncheck();
        assert.equal(await page.locator('.rp-feature-check:visible').evaluate(node => node.indeterminate), true);
        await page.locator('[data-state=changed]').click(); await search('');
        assert.equal(await page.locator('.rp-permission:visible').count(), 3);
        assert.equal(await page.locator('#changeSummary').innerText(), 'Thêm 2 · Bỏ 1');
        await page.locator('#reviewChanges').click();
        assert.match(await page.locator('#changesList').innerText(), /Cấp thêm 2 quyền/);
        assert.match(await page.locator('#changesList').innerText(), /Bỏ 1 quyền/);
        await page.screenshot({ path: path.join(output, 'review-changes.png') });
        await page.keyboard.press('Escape'); await save();
        assert.equal(await page.locator('#selectedPermissionCount').innerText(), '4');
        await checkbox('pos.order.refund').uncheck();
        const currentRole = await page.locator('#rolePicker').inputValue();
        page.once('dialog', dialog => dialog.dismiss()); await page.locator('#rolePicker').selectOption('0');
        assert.equal(await page.locator('#rolePicker').inputValue(), currentRole);
        await page.locator('#undoChanges').click();
        assert.equal(await checkbox('pos.order.refund').isChecked(), true);
        assert.equal(await page.locator('#changedPermissionCount').innerText(), '0');
        await page.locator('[data-state=selected]').click();
        assert.equal(await page.locator('.rp-permission:visible').count(), 4);
        await page.locator('[data-state=unselected]').click();
        assert.equal(await page.locator('.permission-checkbox:checked:visible').count(), 0);
        await clear(); await search('khong-co-quyen-nay'); assert.equal(await page.locator('#noResults').isVisible(), true);
        await page.locator('#resetSearch').click();
        const feature = page.locator('.rp-feature').filter({ has: page.locator('h3', { hasText: /^In tem sản phẩm$/ }) });
        await feature.locator('.rp-feature-check').check();
        assert.equal(await checkbox('system.productlabel.manage').isChecked(), true);
        await feature.locator('.rp-feature-check').uncheck();
        assert.equal(await checkbox('system.productlabel.print').isChecked(), false);
        await page.locator('#undoChanges').click();
        await clear(); await page.locator('.rp-group-tab').filter({ hasText: 'Bán hàng & thu ngân' }).click();
        await page.evaluate(() => scrollTo(0, 0));
        await page.screenshot({ path: path.join(output, 'permissions-final.png') });
        assert.deepEqual(errors, []);
        console.log('PASS additions/removals, review/Escape, dirty role switch, undo, state/group filters, tri-state controls, five widths and zero JS errors.');
    } catch (error) { await page.screenshot({ path: path.join(output, 'failure.png'), fullPage: true }); throw error; }
    finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
